<?php

defined('SYSPATH') or die('No direct access allowed.');

return [
    'title' => 'CRESENITY',
    'lang' => 'id',
    'admin_email' => 'contact@cresenitytech.com',
    'set_timezone' => true,
    'default_timezone' => 'Asia/Jakarta',
    'multilang' => true,
    'update_last_request' => true,
    'date_formatted' => 'Y-m-d',
    'long_date_formatted' => 'Y-m-d H:i:s',
    'require_js' => true,
    'requireJs' => true,
    'merge_js' => false,
    'minify_js' => false,
    'merge_css' => false,
    'minify_css' => false,
    'have_user_login' => true,
    'have_user_access' => true,
    'have_user_permission' => true,
    'have_clock' => false,
    'change_theme' => false,
    'smtp_host' => 'smtp.sendgrid.net',
    'smtp_port' => '25',
    'smtp_secure' => 'false',
    'smtp_username' => 'apikey',
    'smtp_password' => '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',
    'smtp_from' => 'no-reply@core.capp',

    'auth' => [
        'guard' => 'web',
        'middleware' => ['web'],
        'passwords' => 'users',
        'username' => 'username',
        'email' => 'email',
        'hasher' => 'md5',
        'views' => true,
        'home' => '/home',
        'prefix' => '',
        'domain' => null,
        'limiters' => [
            'login' => null,
        ],
        'features' => [
            CApp_Auth_Features::registration(),
            CApp_Auth_Features::resetPasswords(),
            CApp_Auth_Features::emailVerification(),
            CApp_Auth_Features::updateProfileInformation(),
            CApp_Auth_Features::updatePasswords(),
            //CApp_Auth_Features::twoFactorAuthentication(),
        ],
    ],
];
