<?php

return array(
    "client_modules" => array(
        'json2',
        'excanvas',
        'canvas-to-blob',
        'load-image',
        'jquery',
        'bootstrap',
        'font-awesome',
        'jquery-ui-1.12.1.custom',
        'jquery.dialog2',
        'slimscroll',
        'fileupload',
        'wysihtml5',
        'notify',
        'bootbox',
        'form',
        'controls',
        'event',
        'effects',
        'validation',
        'easing',
        'chosen',
        'uniform',
        'select2',
        'modernizr',
    ),
    "js" => array(
        "cresenity-legacy/capp.js",
        "cresenity-legacy/cresenity.js",
    ),
    "css" => array(
        "cresenity-legacy/cresenity.colors.css",
        "cresenity-legacy/cresenity.main.css",
        "cresenity-legacy/cresenity.responsive.css",
        "cresenity-legacy/cresenity.pos.css",
        "cresenity-legacy/cresenity.retail.css",
        "cresenity-legacy/cresenity.widget.css",
        "cresenity-legacy/cresenity.table.css",
        "cresenity-legacy/cresenity.css",
        "cresenity-legacy/cresenity-compat.css",
    ),
);
