<?php

return [
    'client_modules' => [
        'json2',
        'excanvas',
        'canvas-to-blob',
        'load-image',
        'jquery',
        'bootstrap',
        'font-awesome',
        'jquery-ui-1.12.1.custom',
        'jquery.dialog2',
        'slimscroll',
        'fileupload',
        'wysihtml5',
        'notify',
        'bootbox',
        'form',
        'controls',
        'event',
        'effects',
        'validation',
        'easing',
        'chosen',
        'uniform',
        'select2',
        'modernizr',
    ],
    'js' => [
        'capp.js',
        'cresenity.js',
    ],
    'css' => [
        'cresenity.colors.css',
        'cresenity.main.css',
        'cresenity.responsive.css',
        'cresenity.pos.css',
        'cresenity.retail.css',
        'cresenity.widget.css',
        'cresenity.table.css',
        'cresenity.css',
        'cresenity/cresenity.bs3.css',
        'cresenity/cresenity.main.bs3.css',
    ],
];
