<?php
return array(
	array(
		"name"=>"room_building",
		"label"=>"Building",
		"controller"=>"hotel_room_building",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_room_building',
				'label'=>'Add',
				'controller'=>'hotel_room_building',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_room_building',
				'label'=>'Edit',
				'controller'=>'hotel_room_building',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_room_building',
				'label'=>'Delete',
				'controller'=>'hotel_room_building',
				'method'=>'delete',
			),
		),
		"requirements"=>array(
			"have_room_building"=>true,
		),
	),
	array(
		"name"=>"room_floor",
		"label"=>"Floor",
		"controller"=>"hotel_room_floor",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_room_floor',
				'label'=>'Add',
				'controller'=>'hotel_room_floor',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_room_floor',
				'label'=>'Edit',
				'controller'=>'hotel_room_floor',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_room_floor',
				'label'=>'Delete',
				'controller'=>'hotel_room_floor',
				'method'=>'delete',
			),
		),
		"requirements"=>array(
			"have_room_floor"=>true,
		),
	),
	array(
		"name"=>"room_type",
		"label"=>"Type",
		"controller"=>"hotel_room_type",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_room_type',
				'label'=>'Add',
				'controller'=>'hotel_room_type',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_room_type',
				'label'=>'Edit',
				'controller'=>'hotel_room_type',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_room_type',
				'label'=>'Delete',
				'controller'=>'hotel_room_type',
				'method'=>'delete',
			),
		),
		"requirements"=>array(
			"have_room_type"=>true,
		),
	),
	array(
		"name"=>"room_amenities",
		"label"=>"Amenities",
		"controller"=>"hotel_room_amenities",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_room_amenities',
				'label'=>'Add',
				'controller'=>'hotel_room_amenities',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_room_amenities',
				'label'=>'Edit',
				'controller'=>'hotel_room_amenities',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_room_amenities',
				'label'=>'Delete',
				'controller'=>'hotel_room_amenities',
				'method'=>'delete',
			),
		),
		"requirements"=>array(
			"have_room_amenities"=>true,
		),
	),
	array(
		"name"=>"hotel_room",
		"label"=>"Room",
		"controller"=>"hotel_room",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_room',
				'label'=>'Add',
				'controller'=>'hotel_room',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_room',
				'label'=>'Edit',
				'controller'=>'hotel_room',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_room',
				'label'=>'Delete',
				'controller'=>'hotel_room',
				'method'=>'delete',
			),
		),
	),
	array(
		"name"=>"hotel_rate_plan",
		"label"=>"Rate Plan",
		"controller"=>"hotel_rate_plan",
		"method"=>"index",
		'action'=>array(
			array(
				'name'=>'add_hotel_rate_plan',
				'label'=>'Add',
				'controller'=>'hotel_rate_plan',
				'method'=>'add',
			),
			array(
				'name'=>'edit_hotel_rate_plan',
				'label'=>'Edit',
				'controller'=>'hotel_rate_plan',
				'method'=>'edit',
			),
			array(
				'name'=>'delete_hotel_rate_plan',
				'label'=>'Delete',
				'controller'=>'hotel_rate_plan',
				'method'=>'delete',
			),
		),
	),
	
);
