<?php
/**
 * @method string active1DayUsers()
 * @method string active28DayUsers()
 * @method string active7DayUsers()
 * @method string activeUsers()
 * @method string adUnitExposure()
 * @method string addToCarts()
 * @method string averagePurchaseRevenue()
 * @method string averagePurchaseRevenuePerPayingUser()
 * @method string averagePurchaseRevenuePerUser()
 * @method string averageRevenuePerUser()
 * @method string averageSessionDuration()
 * @method string cartToViewRate()
 * @method string checkouts()
 * @method string cohortActiveUsers()
 * @method string cohortTotalUsers()
 * @method string conversions()
 * @method string crashAffectedUsers()
 * @method string crashFreeUsersRate()
 * @method string dauPerMau()
 * @method string dauPerWau()
 * @method string ecommercePurchases()
 * @method string engagedSessions()
 * @method string engagementRate()
 * @method string eventCount()
 * @method string eventCountPerUser()
 * @method string eventValue()
 * @method string eventsPerSession()
 * @method string firstTimePurchaserConversionRate()
 * @method string firstTimePurchasers()
 * @method string firstTimePurchasersPerNewUser()
 * @method string itemListClickThroughRate()
 * @method string itemListClicks()
 * @method string itemListViews()
 * @method string itemPromotionClickThroughRate()
 * @method string itemPromotionClicks()
 * @method string itemPromotionViews()
 * @method string itemPurchaseQuantity()
 * @method string itemRevenue()
 * @method string itemViews()
 * @method string newUsers()
 * @method string publisherAdClicks()
 * @method string publisherAdImpressions()
 * @method string purchaseRevenue()
 * @method string purchaseToViewRate()
 * @method string purchaserConversionRate()
 * @method string screenPageViews()
 * @method string screenPageViewsPerSession()
 * @method string sessions()
 * @method string sessionsPerUser()
 * @method string totalAdRevenue()
 * @method string totalPurchasers()
 * @method string totalRevenue()
 * @method string totalUsers()
 * @method string transactions()
 * @method string transactionsPerPurchaser()
 * @method string userEngagementDuration()
 * @method string wauPerMau()
 */
class CAnalytics_Google_MetaData_ApiSchema_Metrics {
    public static function __callStatic($method, $args) {
        return $method;
    }
}
