<?php

use Mockery as m;
use PHPUnit\Framework\TestCase;

/**
 * Tests for the fluent CDatabase_Schema_Blueprint API itself: which columns/commands
 * get recorded, how index names are generated by convention, and how the "implied"
 * add/change commands and fluent column indexes get added when the blueprint is
 * compiled. These tests inspect the Blueprint's public introspection methods
 * (getColumns()/getCommands()/getAddedColumns()/getChangedColumns()) directly, and
 * fall back to compiling against the MySQL grammar (with a mocked Connection, no real
 * PDO) only where a behavior can only be observed through toSql().
 */
class DatabaseSchemaBuilderTest extends TestCase {
    protected function tearDown(): void {
        m::close();
    }

    protected function getConnection() {
        $connection = m::mock(CDatabase_Connection::class);
        $connection->shouldReceive('getConfig')->andReturn(null)->byDefault();
        $connection->shouldReceive('getTablePrefix')->andReturn('');
        $connection->shouldReceive('usingNativeSchemaOperations')->andReturn(true);

        return $connection;
    }

    protected function getGrammar($connection = null) {
        $grammar = new CDatabase_Schema_Grammar_MySqlGrammar();
        $grammar->setConnection($connection ?: $this->getConnection());

        return $grammar;
    }

    public function testCreateAddsCreateCommand() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->create();

        $this->assertCount(1, $blueprint->getCommands());
        $this->assertSame('create', $blueprint->getCommands()[0]->name);
    }

    public function testGetTableReturnsTheTableName() {
        $blueprint = new CDatabase_Schema_Blueprint('users');

        $this->assertSame('users', $blueprint->getTable());
    }

    public function testAddColumnStoresTypeNameAndParameters() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('name', 100);

        $columns = $blueprint->getColumns();
        $this->assertCount(1, $columns);
        $this->assertSame('string', $columns[0]->type);
        $this->assertSame('name', $columns[0]->name);
        $this->assertSame(100, $columns[0]->length);
    }

    public function testStringUsesDefaultStringLengthWhenNotSpecified() {
        $original = CDatabase_Schema_Builder::$defaultStringLength;
        CDatabase_Schema_Builder::$defaultStringLength = 191;

        try {
            $blueprint = new CDatabase_Schema_Blueprint('users');
            $blueprint->string('name');

            $this->assertSame(191, $blueprint->getColumns()[0]->length);
        } finally {
            CDatabase_Schema_Builder::$defaultStringLength = $original;
        }
    }

    public function testIncrementsCreatesUnsignedAutoIncrementingInteger() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->increments('id');

        $column = $blueprint->getColumns()[0];
        $this->assertSame('integer', $column->type);
        $this->assertTrue($column->autoIncrement);
        $this->assertTrue($column->unsigned);
    }

    public function testIncrementsFamilyMapToExpectedIntegerTypes() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->tinyIncrements('a');
        $blueprint->smallIncrements('b');
        $blueprint->mediumIncrements('c');
        $blueprint->bigIncrements('d');

        $columns = $blueprint->getColumns();
        $this->assertSame('tinyInteger', $columns[0]->type);
        $this->assertSame('smallInteger', $columns[1]->type);
        $this->assertSame('mediumInteger', $columns[2]->type);
        $this->assertSame('bigInteger', $columns[3]->type);

        foreach ($columns as $column) {
            $this->assertTrue($column->autoIncrement);
            $this->assertTrue($column->unsigned);
        }
    }

    public function testUnsignedIntegerVariantsSetTheUnsignedFlag() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->unsignedInteger('a');
        $blueprint->unsignedTinyInteger('b');
        $blueprint->unsignedSmallInteger('c');
        $blueprint->unsignedMediumInteger('d');
        $blueprint->unsignedBigInteger('e');

        foreach ($blueprint->getColumns() as $column) {
            $this->assertTrue($column->unsigned, "column {$column->name} should be unsigned");
            $this->assertFalse($column->autoIncrement);
        }
    }

    public function testDecimalDefaultsToTotalEightPlacesTwo() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->decimal('amount');

        $column = $blueprint->getColumns()[0];
        $this->assertSame(8, $column->total);
        $this->assertSame(2, $column->places);
        $this->assertNull($column->unsigned);
    }

    public function testUnsignedDecimalSetsUnsignedFlag() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->unsignedDecimal('amount', 5, 1);

        $column = $blueprint->getColumns()[0];
        $this->assertSame(5, $column->total);
        $this->assertSame(1, $column->places);
        $this->assertTrue($column->unsigned);
    }

    public function testTimestampsAddsNullableCreatedAndUpdatedColumns() {
        // NB: CF's own audit-column convention (see CModel::CREATED / CModel::UPDATED)
        // is 'created' / 'updated', NOT Laravel's 'created_at' / 'updated_at' - so this
        // divergence from upstream Laravel is intentional.
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->timestamps();

        $columns = $blueprint->getColumns();
        $this->assertCount(2, $columns);
        $this->assertSame('created', $columns[0]->name);
        $this->assertSame('timestamp', $columns[0]->type);
        $this->assertTrue($columns[0]->nullable);
        $this->assertSame('updated', $columns[1]->name);
        $this->assertTrue($columns[1]->nullable);
    }

    public function testNullableTimestampsIsAnAliasForTimestamps() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->nullableTimestamps();

        $columns = $blueprint->getColumns();
        $this->assertSame('created', $columns[0]->name);
        $this->assertSame('updated', $columns[1]->name);
    }

    public function testTimestampsTzUsesCreatedUpdatedNaming() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->timestampsTz();

        $columns = $blueprint->getColumns();
        $this->assertSame('created', $columns[0]->name);
        $this->assertSame('timestampTz', $columns[0]->type);
        $this->assertSame('updated', $columns[1]->name);
    }

    public function testDropTimestampsColumnNamesMatchTimestamps() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->dropTimestamps();

        $command = $blueprint->getCommands()[0];
        $this->assertSame('dropColumn', $command->name);
        $this->assertSame(['created', 'updated'], $command->columns);
    }

    public function testSoftDeletesDefaultColumnMatchesDropSoftDeletes() {
        // Unlike timestamps()/dropTimestamps(), softDeletes()/dropSoftDeletes() agree on
        // the column name ('deleted_at'), so dropping actually works as expected here.
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->softDeletes();
        $softDeleteColumn = $blueprint->getColumns()[0];

        $dropBlueprint = new CDatabase_Schema_Blueprint('users');
        $dropBlueprint->dropSoftDeletes();
        $dropCommand = $dropBlueprint->getCommands()[0];

        $this->assertSame('deleted_at', $softDeleteColumn->name);
        $this->assertTrue($softDeleteColumn->nullable);
        $this->assertSame(['deleted_at'], $dropCommand->columns);
    }

    public function testRememberTokenIsNullableStringOfLength100() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->rememberToken();

        $column = $blueprint->getColumns()[0];
        $this->assertSame('remember_token', $column->name);
        $this->assertSame(100, $column->length);
        $this->assertTrue($column->nullable);
    }

    public function testMorphsAddsUnsignedIntegerTypeColumnAndIndex() {
        $blueprint = new CDatabase_Schema_Blueprint('posts');
        $blueprint->morphs('taggable');

        $columns = $blueprint->getColumns();
        $this->assertSame('taggable_id', $columns[0]->name);
        $this->assertSame('integer', $columns[0]->type);
        $this->assertTrue($columns[0]->unsigned);
        $this->assertSame('taggable_type', $columns[1]->name);
        $this->assertSame('string', $columns[1]->type);

        $command = $blueprint->getCommands()[0];
        $this->assertSame('index', $command->name);
        $this->assertSame(['taggable_id', 'taggable_type'], $command->columns);
    }

    public function testNullableMorphsColumnsAreNullable() {
        $blueprint = new CDatabase_Schema_Blueprint('posts');
        $blueprint->nullableMorphs('taggable');

        $columns = $blueprint->getColumns();
        $this->assertTrue($columns[0]->nullable);
        $this->assertTrue($columns[1]->nullable);
    }

    public function testIndexNameFollowsTableColumnsTypeConvention() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->index(['first_name', 'last_name']);

        $command = $blueprint->getCommands()[0];
        $this->assertSame('users_first_name_last_name_index', $command->index);
    }

    public function testIndexNameSanitizesDashesAndDots() {
        $blueprint = new CDatabase_Schema_Blueprint('my-schema.users');
        $blueprint->index('email');

        $command = $blueprint->getCommands()[0];
        $this->assertSame('my_schema_users_email_index', $command->index);
    }

    public function testExplicitIndexNameIsRespected() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->unique('email', 'custom_unique_name');

        $command = $blueprint->getCommands()[0];
        $this->assertSame('custom_unique_name', $command->index);
    }

    public function testForeignReturnsForeignKeyDefinition() {
        $blueprint = new CDatabase_Schema_Blueprint('posts');
        $foreign = $blueprint->foreign('user_id')->references('id')->on('users');

        $this->assertInstanceOf(CDatabase_Schema_ForeignKeyDefinition::class, $foreign);
        $this->assertSame('posts_user_id_foreign', $foreign->index);
        $this->assertSame('id', $foreign->references);
        $this->assertSame('users', $foreign->on);
    }

    public function testDropIndexCommandsBuildNameFromColumnsArray() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->dropPrimary(['id']);
        $blueprint->dropUnique(['email']);
        $blueprint->dropIndex(['name']);
        $blueprint->dropForeign(['user_id']);

        $commands = $blueprint->getCommands();
        $this->assertSame('users_id_primary', $commands[0]->index);
        $this->assertSame('users_email_unique', $commands[1]->index);
        $this->assertSame('users_name_index', $commands[2]->index);
        $this->assertSame('users_user_id_foreign', $commands[3]->index);
    }

    public function testDropIndexCommandsAcceptAnExplicitIndexName() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->dropUnique('custom_index_name');

        $command = $blueprint->getCommands()[0];
        $this->assertSame('custom_index_name', $command->index);
    }

    public function testDropColumnAcceptsAnArrayOrVariadicArguments() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->dropColumn(['a', 'b']);
        $blueprint2 = new CDatabase_Schema_Blueprint('users');
        $blueprint2->dropColumn('a', 'b');

        $this->assertSame(['a', 'b'], $blueprint->getCommands()[0]->columns);
        $this->assertSame(['a', 'b'], $blueprint2->getCommands()[0]->columns);
    }

    public function testRenameColumnAddsRenameColumnCommand() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->renameColumn('old', 'new');

        $command = $blueprint->getCommands()[0];
        $this->assertSame('renameColumn', $command->name);
        $this->assertSame('old', $command->from);
        $this->assertSame('new', $command->to);
    }

    public function testGetAddedColumnsExcludesColumnsMarkedAsChanged() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('name');
        $blueprint->string('email')->change();

        $this->assertCount(1, $blueprint->getAddedColumns());
        $this->assertSame('name', $blueprint->getAddedColumns()[0]->name);
    }

    public function testGetChangedColumnsOnlyReturnsColumnsMarkedAsChanged() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('name');
        $blueprint->string('email')->change();

        // NB: getChangedColumns() uses array_filter() without re-indexing, so the
        // surviving element keeps its original array key (1, not 0) - use array_values()
        // to get a clean list.
        $changed = array_values($blueprint->getChangedColumns());
        $this->assertCount(1, $changed);
        $this->assertSame('email', $changed[0]->name);
    }

    public function testRemoveColumnDropsItFromTheBlueprint() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('name');
        $blueprint->string('email');
        $blueprint->removeColumn('name');

        $columns = $blueprint->getColumns();
        $this->assertCount(1, $columns);
        $this->assertSame('email', $columns[0]->name);
    }

    public function testFluentUniqueOnColumnAddsAnImpliedUniqueCommand() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->create();
        $blueprint->string('email')->unique();

        $connection = $this->getConnection();
        $statements = $blueprint->toSql($connection, $this->getGrammar($connection));

        // The implied unique index is compiled as a separate "alter table ... add unique"
        // statement, after the "create table" statement.
        $this->assertCount(2, $statements);
        $this->assertSame(
            'create table `users` (`email` varchar(255) not null)',
            $statements[0]
        );
        $this->assertSame(
            'alter table `users` add unique `users_email_unique`(`email`)',
            $statements[1]
        );
    }

    public function testAddingColumnsToAnExistingTableImpliesAnAddCommand() {
        // No ->create() call: this blueprint represents altering an existing table, so
        // addImpliedCommands() should prepend an "add" command for the new column.
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('nickname');

        $connection = $this->getConnection();
        $statements = $blueprint->toSql($connection, $this->getGrammar($connection));

        $this->assertSame(
            'alter table `users` add `nickname` varchar(255) not null',
            $statements[0]
        );
    }

    public function testChangingAColumnOnAnExistingTableImpliesAChangeCommand() {
        $blueprint = new CDatabase_Schema_Blueprint('users');
        $blueprint->string('name')->nullable()->change();

        // addImpliedCommands() (which prepends the "change" command for changed columns)
        // only runs as part of toSql() - it is protected, so invoke it via reflection to
        // observe the resulting command list without needing a grammar that can actually
        // compile a "change" statement.
        $method = new ReflectionMethod($blueprint, 'addImpliedCommands');
        $method->setAccessible(true);
        $method->invoke($blueprint);

        $this->assertSame('change', $blueprint->getCommands()[0]->name);
    }
}
