<?php



return array(
	array(
		"name"=>"dashboard",
		"label"=>"Dashboard",
		"controller"=>"home",
		"method"=>"index",
		"icon"=>"home",
	),
	array(
		"name"=>"cashier",
		"label"=>"Cashier",
		"controller"=>"resto",
		"method"=>"index",
		"icon"=>"desktop",
	),
	
	array(
		"name"=>"resto_menu",
		"label"=>"Menu",
		"icon"=>"food",
		"subnav"=>array(
			array(
				"name"=>"resto_menu_category",
				"label"=>"Menu Category",
				"controller"=>"resto_menu_category",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_menu_category',
						'label'=>'Add',
						'controller'=>'resto_menu_category',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_menu_category',
						'label'=>'Edit',
						'controller'=>'resto_menu_category',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_menu_category',
						'label'=>'Delete',
						'controller'=>'resto_menu_category',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_menu_subcategory",
				"label"=>"Menu Subcategory",
				"controller"=>"resto_menu_subcategory",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_menu_subcategory',
						'label'=>'Add',
						'controller'=>'resto_menu_subcategory',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_menu_subcategory',
						'label'=>'Edit',
						'controller'=>'resto_menu_subcategory',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_menu_subcategory',
						'label'=>'Delete',
						'controller'=>'resto_menu_subcategory',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_menu",
				"label"=>"Menu",
				"controller"=>"resto_menu",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_menu',
						'label'=>'Add',
						'controller'=>'resto_menu',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_menu',
						'label'=>'Edit',
						'controller'=>'resto_menu',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_menu',
						'label'=>'Delete',
						'controller'=>'resto_menu',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_menu_note",
				"label"=>"Menu Note",
				"controller"=>"resto_menu_note",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_menu_note',
						'label'=>'Add',
						'controller'=>'resto_menu_note',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_menu_note',
						'label'=>'Edit',
						'controller'=>'resto_menu_note',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_menu_note',
						'label'=>'Delete',
						'controller'=>'resto_menu_note',
						'method'=>'delete',
					),
					
				),
			),
		),
	),
	array(
		"name"=>"member_data",
		"label"=>"Member",
		"icon"=>"user",
		"subnav"=>array(
			array(
				"name"=>"resto_member_type",
				"label"=>"Member Type",
				"controller"=>"resto_member_type",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_member_type',
						'label'=>'Add',
						'controller'=>'resto_member_type',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_member_type',
						'label'=>'Edit',
						'controller'=>'resto_member_type',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_member_type',
						'label'=>'Delete',
						'controller'=>'resto_member_type',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_member",
				"label"=>"Member",
				"controller"=>"resto_member",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_member',
						'label'=>'Add',
						'controller'=>'resto_member',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_member',
						'label'=>'Edit',
						'controller'=>'resto_member',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_member',
						'label'=>'Delete',
						'controller'=>'resto_member',
						'method'=>'delete',
					),
					
				),
			),
		),
	),
	array(
		"name"=>"promo_data",
		"label"=>"Promo",
		"icon"=>"star",
		"subnav"=>array(
			array(
				"name"=>"resto_promo",
				"label"=>"Promo Manager",
				"controller"=>"resto_promo",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_promo',
						'label'=>'Add',
						'controller'=>'resto_promo',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_promo',
						'label'=>'Edit',
						'controller'=>'resto_promo',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_promo',
						'label'=>'Delete',
						'controller'=>'resto_promo',
						'method'=>'delete',
					),
					
				),
			),
		),
	),
	array(
		"name"=>"config_data",
		"label"=>"Config",
		"icon"=>"cogs",
		"subnav"=>array(
			array(
				"name"=>"resto_payment_type_group",
				"label"=>"Payment Type Group",
				"controller"=>"resto_payment_type_group",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_payment_type_group',
						'label'=>'Add',
						'controller'=>'resto_payment_type_group',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_payment_type_group',
						'label'=>'Edit',
						'controller'=>'resto_payment_type_group',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_payment_type_group',
						'label'=>'Delete',
						'controller'=>'resto_payment_type_group',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_payment_type",
				"label"=>"Payment Type",
				"controller"=>"resto_payment_type",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_payment_type',
						'label'=>'Add',
						'controller'=>'resto_payment_type',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_payment_type',
						'label'=>'Edit',
						'controller'=>'resto_payment_type',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_payment_type',
						'label'=>'Delete',
						'controller'=>'resto_payment_type',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_floor",
				"label"=>"Floor",
				"controller"=>"resto_floor",
				"method"=>"index",
                "requirements"=>array(
                    "have_resto_floor"=>true,
                ),
				'action'=>array(
					array(
						'name'=>'add_resto_floor',
						'label'=>'Add',
						'controller'=>'resto_floor',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_floor',
						'label'=>'Edit',
						'controller'=>'resto_floor',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_floor',
						'label'=>'Delete',
						'controller'=>'resto_floor',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_table",
				"label"=>"Table",
				"controller"=>"resto_table",
				"method"=>"index",
                "requirements"=>array(
                    "have_resto_table"=>true,
                ),
				'action'=>array(
					array(
						'name'=>'add_resto_table',
						'label'=>'Add',
						'controller'=>'resto_table',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_table',
						'label'=>'Edit',
						'controller'=>'resto_table',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_table',
						'label'=>'Delete',
						'controller'=>'resto_table',
						'method'=>'delete',
					),
					
				),
			),
			array(
				"name"=>"resto_kitchen",
				"label"=>"Kitchen",
				"controller"=>"resto_kitchen",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'add_resto_kitchen',
						'label'=>'Add',
						'controller'=>'resto_kitchen',
						'method'=>'add',
					),
					array(
						'name'=>'edit_resto_kitchen',
						'label'=>'Edit',
						'controller'=>'resto_kitchen',
						'method'=>'edit',
					),
					array(
						'name'=>'delete_resto_kitchen',
						'label'=>'Delete',
						'controller'=>'resto_kitchen',
						'method'=>'delete',
					),
					
				),
			),
		),
	),
	array(
		"name"=>"log_list",
		"label"=>"Log",
		"icon"=>"file-text",
		"subnav"=>array(
			array(
				"name"=>"log_login_menu",
				"label"=>"Login",
				"subnav"=>array(
					array(
						"name"=>"log_login",
						"label"=>"Login Success Log",
						"controller"=>"log_login",
						"method"=>"index",
						'action'=>array(
							array(
								'name'=>'download_xls_log_login',
								'label'=>'Download XLS',
							),
						),
					),
					
				),
			),
			array(
				"name"=>"log_request",
				"label"=>"Request Log",
				"controller"=>"log_request",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'download_xls_log_request',
						'label'=>'Download XLS',
					),
				),
			),
			array(
				"name"=>"log_activity",
				"label"=>"Activity Log",
				"controller"=>"log_activity",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'download_xls_log_activity',
						'label'=>'Download XLS',
					),
				),
			),
			
		),
	),//end log_list
	
	array(
		"name"=>"setting_list",
		"label"=>"Setting",
		"icon"=>"cog",
		"subnav"=>array(
			array(
				"name"=>"access",
				"label"=>"Access",
				"subnav"=>array(
					array(
						"name"=>"roles",
						"label"=>"Roles",
						"controller"=>"roles",
						"method"=>"index",
						'action'=>array(
							array(
								'name'=>'add_roles',
								'label'=>'Add',
								'controller'=>'roles',
								'method'=>'add',
							),
							array(
								'name'=>'edit_roles',
								'label'=>'Edit',
								'controller'=>'roles',
								'method'=>'edit',
							),
							array(
								'name'=>'delete_roles',
								'label'=>'Delete',
								'controller'=>'roles',
								'method'=>'delete',
							),
						),//end action roles
					),
					array(
						"name"=>"users",
						"label"=>"Users",
						"controller"=>"users",
						"method"=>"index",
						'action'=>array(
							array(
								'name'=>'add_users',
								'label'=>'Add',
								'controller'=>'users',
								'method'=>'add',
							),
							array(
								'name'=>'edit_users',
								'label'=>'Edit',
								'controller'=>'users',
								'method'=>'edit',
							),
							array(
								'name'=>'delete_users',
								'label'=>'Delete',
								'controller'=>'users',
								'method'=>'delete',
							),
						),//end action users
					),
					array(
						"name"=>"user_permission",
						"label"=>"Users Permission",
						"controller"=>"user_permission",
						"method"=>"index",	
					),
				),//end subnav access
			),
			array(
				"name"=>"resto_setting",
				"label"=>"Setting",
				"controller"=>"resto_setting",
				"method"=>"index",
				'action'=>array(
					array(
						'name'=>'edit_resto_setting',
						'label'=>'Edit',
						'controller'=>'resto_setting',
						'method'=>'edit',
					),
				),//end action setting
			),
			array(
				"name"=>"resto_sync",
				"label"=>"Synchronize",
				"controller"=>"client_sync",
				"method"=>"index",
                "requirements"=>array(
                    "have_synchronize"=>true
                ),
			),
			
	
		),
	),//end setting_list
);
