<?php

/**
 * Description of ProcessRunnerResult
 *
 * @author Hery
 */
class CQC_ProcessRunnerResult {

    /**
     *
     * @var string
     */
    protected $output;

    /**
     *
     * @var string
     */
    protected $errorOutput;

    public function __construct($rawOutput, $rawErrorOutput) {
        $output = $rawOutput;
        $errorOutput = $rawErrorOutput;
        
        if (preg_match('/div#framework_error h3/ims', $rawOutput)) {
            //this is exception error generated by framework
            $errorTitle = '';
            if (preg_match("#<title>(.+?)</title>#ims", $rawOutput, $matches)) {
                $errorTitle = carr::get($matches, 1);
            }
            $errorBody = $rawOutput;
            if (preg_match("#<body>(.+?)</body>#ims", $rawOutput, $matches)) {
                $errorBody = carr::get($matches, 1);
            }
            $errorOutput = $errorBody;
        }


        $this->output = $output;
        $this->errorOutput = $errorOutput;
    }

    public function getOutput() {
        return $this->output;
    }

    public function getErrorOutput() {
        return $this->errorOutput;
    }

    public function haveError() {
        return strlen($this->errorOutput) > 0;
    }

}
