<?php
namespace GuzzleHttp\Ring\Exception;

class GuzzleHttp_Ring_Exception_CancelledFutureAccessException extends GuzzleHttp_Ring_Exception_RingException implements GuzzleHttp_Ring_Exception_CancelledException {}
