<?php

class CAnalytics_Google_MetaData_Dimensions {
    public static function achievementId() {
        return [
            'apiName' => 'achievementId',
            'uiName' => 'Achievement ID',
            'category' => 'Other',
            'description' => 'The achieventment ID in a game for an event. Populated by the event parameter \'achievement_id\'.',
            'isCustomDefinition' => false,
        ];
    }

    public static function adFormat() {
        return  [
            'apiName' => 'adFormat',
            'uiName' => 'Ad format',
            'category' => 'Publisher',
            'description' => 'Describes the way ads looked and where they were located. Typical formats include \'Interstitial\', \'Banner\', \'Rewarded\', and \'Native advanced\'.',
            'isCustomDefinition' => false,
        ];
    }

    public static function adSourceName() {
        return [
            'apiName' => 'adSourceName',
            'uiName' => 'Ad source',
            'category' => 'Publisher',
            'description' => 'The source network that served the ad. Typical sources include \'AdMob Network\', \'Liftoff\', \'Facebook Audience Network\', and \'Mediated house ads\'.',
            'isCustomDefinition' => false,
        ];
    }

    public static function all() {
        return [
            'achievementId' => static::achievementId(),
            'adFormat' => static::adFormat(),
            'adSourceName' => static::adSourceName(),
            'adUnitName' => [
                'apiName' => 'adUnitName',
                'uiName' => 'Ad unit',
                'category' => 'Publisher',
                'description' => 'The name you chose to describe this Ad unit. Ad units are containers you place in your apps to show ads to users.',
                'isCustomDefinition' => false,
            ],
            'appVersion' => [
                'apiName' => 'appVersion',
                'uiName' => 'App version',
                'category' => 'Platform / Device',
                'description' => 'The app\'s versionName (Android) or short bundle version (iOS).',
                'isCustomDefinition' => false,
            ],
            'audienceId' => [
                'apiName' => 'audienceId',
                'uiName' => 'Audience ID',
                'category' => 'User',
                'description' => 'The numeric identifier of an Audience. Users are reported in the audiences to which they belonged during the report\'s date range. Current user behavior does not affect historical audience membership in reports.',
                'isCustomDefinition' => false,
            ],
            'audienceName' => [
                'apiName' => 'audienceName',
                'uiName' => 'Audience name',
                'category' => 'User',
                'description' => 'The given name of an Audience. Users are reported in the audiences to which they belonged during the report\'s date range. Current user behavior does not affect historical audience membership in reports.',
                'isCustomDefinition' => false,
            ],
            'brandingInterest' => [
                'apiName' => 'brandingInterest',
                'uiName' => 'Interests',
                'category' => 'Demographics',
                'description' => 'Interests demonstrated by users who are higher in the shopping funnel. Users can be counted in multiple interest categories. For example, \'Shoppers\', \'Lifestyles & Hobbies/Pet Lovers\', or \'Travel/Travel Buffs/Beachbound Travelers\'.',
                'isCustomDefinition' => false,
            ],
            'browser' => [
                'apiName' => 'browser',
                'uiName' => 'Browser',
                'category' => 'Platform / Device',
                'description' => 'The browsers used to view your website.',
                'isCustomDefinition' => false,
            ],
            'campaignId' => [
                'apiName' => 'campaignId',
                'uiName' => 'Campaign ID',
                'category' => 'Attribution',
                'description' => 'The identifier of the marketing campaign. Present only for conversion events.',
                'isCustomDefinition' => false,
            ],
            'campaignName' => [
                'apiName' => 'campaignName',
                'uiName' => 'Campaign',
                'category' => 'Attribution',
                'description' => 'The name of the marketing campaign. Present only for conversion events.',
                'isCustomDefinition' => false,
            ],
            'character' => [
                'apiName' => 'character',
                'uiName' => 'Character',
                'category' => 'Other',
                'description' => 'The player character in a game for an event. Populated by the event parameter \'character\'.',
                'isCustomDefinition' => false,
            ],
            'city' => [
                'apiName' => 'city',
                'uiName' => 'City',
                'category' => 'Geography',
                'description' => 'The city from which the user activity originated.',
                'isCustomDefinition' => false,
            ],
            'cityId' => [
                'apiName' => 'cityId',
                'uiName' => 'City ID',
                'category' => 'Geography',
                'description' => 'The geographic ID of the city from which the user activity originated, derived from their IP address.',
                'isCustomDefinition' => false,
            ],
            'cohort' => [
                'apiName' => 'cohort',
                'uiName' => 'Cohort',
                'category' => 'Cohort',
                'description' => 'The cohort\'s name in the request. A cohort is a set of users who started using your website or app in any consecutive group of days. If a cohort name is not specified in the request, cohorts are named by their zero based index: cohort_0, cohort_1, etc.',
                'isCustomDefinition' => false,
            ],
            'cohortNthDay' => [
                'apiName' => 'cohortNthDay',
                'uiName' => 'Daily cohort',
                'category' => 'Cohort',
                'description' => 'Day offset relative to the firstSessionDate for the users in the cohort. For example, if a cohort is selected with the start and end date of 2020-03-01, then for the date 2020-03-02, cohortNthDay will be 0001.',
                'isCustomDefinition' => false,
            ],
            'cohortNthMonth' => [
                'apiName' => 'cohortNthMonth',
                'uiName' => 'Monthly cohort',
                'category' => 'Cohort',
                'description' => 'Month offset relative to the firstSessionDate for the users in the cohort. Month boundaries align with calendar month boundaries. For example, if a cohort is selected with the start and end date in March 2020, then for any date in April 2020, cohortNthMonth will be 0001.',
                'isCustomDefinition' => false,
            ],
            'cohortNthWeek' => [
                'apiName' => 'cohortNthWeek',
                'uiName' => 'Weekly cohort',
                'category' => 'Cohort',
                'description' => 'Week offset relative to the firstSessionDate for the users in the cohort. Weeks start on Sunday and end on Saturday. For example, if a cohort is selected with the start and end date in the range 2020-11-08 to 2020-11-14, then for the dates in the range 2020-11-15 to 2020-11-21, cohortNthWeek will be 0001.',
                'isCustomDefinition' => false,
            ],
            'contentGroup' => [
                'apiName' => 'contentGroup',
                'uiName' => 'Content group',
                'category' => 'Page / Screen',
                'description' => 'A category that applies to items of published content. Populated by the event parameter \'content_group\'.',
                'isCustomDefinition' => false,
            ],
            'contentId' => [
                'apiName' => 'contentId',
                'uiName' => 'Content ID',
                'category' => 'Page / Screen',
                'description' => 'The identifier of the selected content. Populated by the event parameter \'content_id\'.',
                'isCustomDefinition' => false,
            ],
            'contentType' => [
                'apiName' => 'contentType',
                'uiName' => 'Content type',
                'category' => 'Page / Screen',
                'description' => 'The category of the selected content. Populated by the event parameter \'content_type\'.',
                'isCustomDefinition' => false,
            ],
            'country' => [
                'apiName' => 'country',
                'uiName' => 'Country',
                'category' => 'Geography',
                'description' => 'The country from which the user activity originated.',
                'isCustomDefinition' => false,
            ],
            'countryId' => [
                'apiName' => 'countryId',
                'uiName' => 'Country ID',
                'category' => 'Geography',
                'description' => 'The geographic ID of the country from which the user activity originated, derived from their IP address. Formatted according to ISO 3166-1 alpha-2 standard.',
                'isCustomDefinition' => false,
            ],
            'date' => [
                'apiName' => 'date',
                'uiName' => 'Date',
                'category' => 'Time',
                'description' => 'The date of the event, formatted as YYYYMMDD.',
                'isCustomDefinition' => false,
            ],
            'dateHour' => [
                'apiName' => 'dateHour',
                'uiName' => 'Date + hour (YYYYMMDDHH)',
                'category' => 'Time',
                'description' => 'The combined values of date and hour formatted as YYYYMMDDHH.',
                'isCustomDefinition' => false,
            ],
            'dateHourMinute' => [
                'apiName' => 'dateHourMinute',
                'uiName' => 'Date hour and minute',
                'category' => 'Time',
                'description' => 'The combined values of date, hour, and minute formatted as YYYYMMDDHHMM.',
                'isCustomDefinition' => false,
            ],
            'day' => [
                'apiName' => 'day',
                'uiName' => 'Day',
                'category' => 'Time',
                'description' => 'The day of the month, a two-digit number from 01 to 31.',
                'isCustomDefinition' => false,
            ],
            'dayOfWeek' => [
                'apiName' => 'dayOfWeek',
                'uiName' => 'Day of week',
                'category' => 'Time',
                'description' => 'The day of the week. It returns values in the range [0,6] with Sunday as the first day of the week.',
                'isCustomDefinition' => false,
            ],
            'defaultChannelGrouping' => [
                'apiName' => 'defaultChannelGrouping',
                'uiName' => 'Default channel grouping',
                'category' => 'Attribution',
                'description' => 'The conversion\'s default channel grouping is based primarily on source and medium. An enumeration which includes \'Direct\', \'Organic Search\', \'Paid Social\', \'Organic Social\', \'Email\', \'Affiliates\', \'Referral\', \'Paid Search\', \'Video\', and \'Display\'.',
                'isCustomDefinition' => false,
            ],
            'deviceCategory' => [
                'apiName' => 'deviceCategory',
                'uiName' => 'Device category',
                'category' => 'Platform / Device',
                'description' => 'The type of device: Desktop, Tablet, or Mobile.',
                'isCustomDefinition' => false,
            ],
            'deviceModel' => [
                'apiName' => 'deviceModel',
                'uiName' => 'Device model',
                'category' => 'Platform / Device',
                'description' => 'The mobile device model (example: iPhone 10,6).',
                'isCustomDefinition' => false,
            ],
            'eventName' => [
                'apiName' => 'eventName',
                'uiName' => 'Event name',
                'category' => 'Event',
                'description' => 'The name of the event.',
                'isCustomDefinition' => false,
            ],
            'fileExtension' => [
                'apiName' => 'fileExtension',
                'uiName' => 'File extension',
                'category' => 'Other',
                'description' => 'The extension of the downloaded file (for example, \'pdf\' or \'txt\'). Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'file_extension\'.',
                'isCustomDefinition' => false,
            ],
            'fileName' => [
                'apiName' => 'fileName',
                'uiName' => 'File name',
                'category' => 'Other',
                'description' => 'The page path of the downloaded file (for example, \'/menus/dinner-menu.pdf\'). Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'file_name\'.',
                'isCustomDefinition' => false,
            ],
            'firstSessionDate' => [
                'apiName' => 'firstSessionDate',
                'uiName' => 'First session date',
                'category' => 'User Lifetime',
                'description' => 'The date the user\'s first session occurred, formatted as YYYYMMDD.',
                'isCustomDefinition' => false,
            ],
            'firstUserCampaignId' => [
                'apiName' => 'firstUserCampaignId',
                'uiName' => 'First user campaign ID',
                'category' => 'Traffic Source',
                'description' => 'Identifier of the marketing campaign that first acquired the user. Includes Google Ads Campaigns.',
                'isCustomDefinition' => false,
            ],
            'firstUserCampaignName' => [
                'apiName' => 'firstUserCampaignName',
                'uiName' => 'First user campaign',
                'category' => 'Traffic Source',
                'description' => 'Name of the marketing campaign that first acquired the user. Includes Google Ads and Manual Campaigns.',
                'isCustomDefinition' => false,
            ],
            'firstUserDefaultChannelGrouping' => [
                'apiName' => 'firstUserDefaultChannelGrouping',
                'uiName' => 'First user default channel grouping',
                'category' => 'Traffic Source',
                'description' => 'The default channel grouping that first acquired the user. Default channel grouping is based primarily on source and medium. An enumeration which includes \'Direct\', \'Organic Search\', \'Paid Social\', \'Organic Social\', \'Email\', \'Affiliates\', \'Referral\', \'Paid Search\', \'Video\', and \'Display\'.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsAdGroupId' => [
                'apiName' => 'firstUserGoogleAdsAdGroupId',
                'uiName' => 'First user Google Ads ad group ID',
                'category' => 'Traffic Source',
                'description' => 'The Ad Group Id in Google Ads that first acquired the user.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsAdGroupName' => [
                'apiName' => 'firstUserGoogleAdsAdGroupName',
                'uiName' => 'First user Google Ads ad group name',
                'category' => 'Traffic Source',
                'description' => 'The Ad Group Name in Google Ads that first acquired the user.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsAdNetworkType' => [
                'apiName' => 'firstUserGoogleAdsAdNetworkType',
                'uiName' => 'First user Google Ads ad network type',
                'category' => 'Traffic Source',
                'description' => 'The advertising network that first acquired the user. An enumeration which includes \'Google search\', \'Search partners\', \'Google Display Network\', \'Youtube Search\', \'Youtube Videos\', \'Cross-network\', \'Social\', and \'(universal campaign)\'.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsCampaignType' => [
                'apiName' => 'firstUserGoogleAdsCampaignType',
                'uiName' => 'First user Google Ads campaign type',
                'category' => 'Traffic Source',
                'description' => 'The campaign type of the Google Ads campaign that first acquired the user. Campaign types determine where customers see your ads and the settings and options available to you in Google Ads. Campaign type is an enumeration that includes: Search, Display, Shopping, Video, Discovery, App, Smart, Hotel, Local, and Performance Max. To learn more, see https://support.google.com/google-ads/answer/2567043.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsCreativeId' => [
                'apiName' => 'firstUserGoogleAdsCreativeId',
                'uiName' => 'First user Google Ads creative ID',
                'category' => 'Traffic Source',
                'description' => 'The ID of the Google Ads creative that first acquired the user. Creative IDs identify individual ads.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsKeyword' => [
                'apiName' => 'firstUserGoogleAdsKeyword',
                'uiName' => 'First user Google Ads keyword text',
                'category' => 'Traffic Source',
                'description' => 'The matched keyword that first acquired the user. Keywords are words or phrases describing your product or service that you choose to get your ad in front of the right customers. To learn more about Keywords, see <https://support.google.com/google-ads/answer/6323>.',
                'isCustomDefinition' => false,
            ],
            'firstUserGoogleAdsQuery' => [
                'apiName' => 'firstUserGoogleAdsQuery',
                'uiName' => 'First user Google Ads query',
                'category' => 'Traffic Source',
                'description' => 'The search query that first acquired the user.',
                'isCustomDefinition' => false,
            ],
            'firstUserManualAdContent' => [
                'apiName' => 'firstUserManualAdContent',
                'uiName' => 'First user manual ad content',
                'category' => 'Traffic Source',
                'description' => 'The ad content that first acquired the user. Populated by the utm_content parameter.',
                'isCustomDefinition' => false,
            ],
            'firstUserManualTerm' => [
                'apiName' => 'firstUserManualTerm',
                'uiName' => 'First user manual term',
                'category' => 'Traffic Source',
                'description' => 'The term that first acquired the user. Populated by the utm_term parameter.',
                'isCustomDefinition' => false,
            ],
            'firstUserMedium' => [
                'apiName' => 'firstUserMedium',
                'uiName' => 'First user medium',
                'category' => 'Traffic Source',
                'description' => 'The medium that first acquired the user to your website or app.',
                'isCustomDefinition' => false,
            ],
            'firstUserSource' => [
                'apiName' => 'firstUserSource',
                'uiName' => 'First user source',
                'category' => 'Traffic Source',
                'description' => 'The source that first acquired the user to your website or app.',
                'isCustomDefinition' => false,
            ],
            'firstUserSourcePlatform' => [
                'apiName' => 'firstUserSourcePlatform',
                'uiName' => 'First user source platform',
                'category' => 'Traffic Source',
                'description' => 'The source platform that first acquired the user. Please do not depend on this field returning \'Manual\' for traffic that uses UTMs; this field will update from returning \'Manual\' to returning \'(not set)\' for an upcoming feature launch.',
                'isCustomDefinition' => false,
            ],
            'fullPageUrl' => [
                'apiName' => 'fullPageUrl',
                'uiName' => 'Full page URL',
                'category' => 'Page / Screen',
                'description' => 'The hostname, page path, and query string for web pages visited; for example, the fullPageUrl portion of https://www.example.com/store/contact-us?query_string=true is www.example.com/store/contact-us?query_string=true.',
                'isCustomDefinition' => false,
            ],
            'googleAdsAccountName' => [
                'apiName' => 'googleAdsAccountName',
                'uiName' => 'Google Ads account name',
                'category' => 'Attribution',
                'description' => 'The customer\'s descriptive name in Google Ads for the conversion event\'s campaign. Corresponding to customer.descriptive_name in the Google Ads API.',
                'isCustomDefinition' => false,
            ],
            'googleAdsAdGroupId' => [
                'apiName' => 'googleAdsAdGroupId',
                'uiName' => 'Google Ads ad group ID',
                'category' => 'Attribution',
                'description' => 'The ad group id attributed to the conversion event.',
                'isCustomDefinition' => false,
            ],
            'googleAdsAdGroupName' => [
                'apiName' => 'googleAdsAdGroupName',
                'uiName' => 'Google Ads ad group name',
                'category' => 'Attribution',
                'description' => 'The ad group name attributed to the conversion event.',
                'isCustomDefinition' => false,
            ],
            'googleAdsAdNetworkType' => [
                'apiName' => 'googleAdsAdNetworkType',
                'uiName' => 'Google Ads ad network type',
                'category' => 'Attribution',
                'description' => 'The advertising network type of the conversion. An enumeration which includes \'Google search\', \'Search partners\', \'Google Display Network\', \'Youtube Search\', \'Youtube Videos\', \'Cross-network\', \'Social\', and \'(universal campaign)\'.',
                'isCustomDefinition' => false,
            ],
            'googleAdsCampaignType' => [
                'apiName' => 'googleAdsCampaignType',
                'uiName' => 'Google Ads campaign type',
                'category' => 'Attribution',
                'description' => 'The campaign type for the Google Ads campaign attributed to the conversion event. Campaign types determine where customers see your ads and the settings and options available to you in Google Ads. Campaign type is an enumeration that includes: Search, Display, Shopping, Video, Discovery, App, Smart, Hotel, Local, and Performance Max. To learn more, see https://support.google.com/google-ads/answer/2567043.',
                'isCustomDefinition' => false,
            ],
            'googleAdsCreativeId' => [
                'apiName' => 'googleAdsCreativeId',
                'uiName' => 'Google Ads creative ID',
                'category' => 'Attribution',
                'description' => 'The ID of the Google Ads creative attributed to the conversion event. Creative IDs identify individual ads.',
                'isCustomDefinition' => false,
            ],
            'googleAdsKeyword' => [
                'apiName' => 'googleAdsKeyword',
                'uiName' => 'Google Ads keyword text',
                'category' => 'Attribution',
                'description' => 'The matched keyword that led to the conversion event. Keywords are words or phrases describing your product or service that you choose to get your ad in front of the right customers. To learn more about Keywords, see <https://support.google.com/google-ads/answer/6323>.',
                'isCustomDefinition' => false,
            ],
            'googleAdsQuery' => [
                'apiName' => 'googleAdsQuery',
                'uiName' => 'Google Ads query',
                'category' => 'Attribution',
                'description' => 'The search query that led to the conversion event.',
                'isCustomDefinition' => false,
            ],
            'groupId' => [
                'apiName' => 'groupId',
                'uiName' => 'Group ID',
                'category' => 'Other',
                'description' => 'The player group ID in a game for an event. Populated by the event parameter \'group_id\'.',
                'isCustomDefinition' => false,
            ],
            'hostName' => [
                'apiName' => 'hostName',
                'uiName' => 'Hostname',
                'category' => 'Page / Screen',
                'description' => 'Includes the subdomain and domain names of a URL; for example, the Host Name of www.example.com/contact.html is www.example.com.',
                'isCustomDefinition' => false,
            ],
            'hour' => [
                'apiName' => 'hour',
                'uiName' => 'Hour',
                'category' => 'Time',
                'description' => 'The two-digit hour of the day that the event was logged. This dimension ranges from 0-23 and is reported in your property\'s timezone.',
                'isCustomDefinition' => false,
            ],
            'isConversionEvent' => [
                'apiName' => 'isConversionEvent',
                'uiName' => 'Is conversion event',
                'category' => 'Event',
                'description' => 'The string \'true\' if the event is a conversion. Events are marked as conversions at collection time; changes to an event\'s conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.',
                'isCustomDefinition' => false,
            ],
            'itemBrand' => [
                'apiName' => 'itemBrand',
                'uiName' => 'Item brand',
                'category' => 'Ecommerce',
                'description' => 'Brand name of the item.',
                'isCustomDefinition' => false,
            ],
            'itemCategory' => [
                'apiName' => 'itemCategory',
                'uiName' => 'Item category',
                'category' => 'Ecommerce',
                'description' => 'The hierarchical category in which the item is classified. For example, in Apparel/Mens/Summer/Shirts/T-shirts, Apparel is the item category.',
                'isCustomDefinition' => false,
            ],
            'itemCategory2' => [
                'apiName' => 'itemCategory2',
                'uiName' => 'Item category 2',
                'category' => 'Ecommerce',
                'description' => 'The hierarchical category in which the item is classified. For example, in Apparel/Mens/Summer/Shirts/T-shirts, Mens is the item category 2.',
                'isCustomDefinition' => false,
            ],
            'itemCategory3' => [
                'apiName' => 'itemCategory3',
                'uiName' => 'Item category 3',
                'category' => 'Ecommerce',
                'description' => 'The hierarchical category in which the item is classified. For example, in Apparel/Mens/Summer/Shirts/T-shirts, Summer is the item category 3.',
                'isCustomDefinition' => false,
            ],
            'itemCategory4' => [
                'apiName' => 'itemCategory4',
                'uiName' => 'Item category 4',
                'category' => 'Ecommerce',
                'description' => 'The hierarchical category in which the item is classified. For example, in Apparel/Mens/Summer/Shirts/T-shirts, Shirts is the item category 4.',
                'isCustomDefinition' => false,
            ],
            'itemCategory5' => [
                'apiName' => 'itemCategory5',
                'uiName' => 'Item category 5',
                'category' => 'Ecommerce',
                'description' => 'The hierarchical category in which the item is classified. For example, in Apparel/Mens/Summer/Shirts/T-shirts, T-shirts is the item category 5.',
                'isCustomDefinition' => false,
            ],
            'itemId' => [
                'apiName' => 'itemId',
                'uiName' => 'Item ID',
                'category' => 'Ecommerce',
                'description' => 'The ID of the item.',
                'isCustomDefinition' => false,
            ],
            'itemListId' => [
                'apiName' => 'itemListId',
                'uiName' => 'Item list ID',
                'category' => 'Ecommerce',
                'description' => 'The ID of the item list.',
                'isCustomDefinition' => false,
            ],
            'itemListName' => [
                'apiName' => 'itemListName',
                'uiName' => 'Item list name',
                'category' => 'Ecommerce',
                'description' => 'The name of the item list.',
                'isCustomDefinition' => false,
            ],
            'itemName' => [
                'apiName' => 'itemName',
                'uiName' => 'Item name',
                'category' => 'Ecommerce',
                'description' => 'The name of the item.',
                'isCustomDefinition' => false,
            ],
            'itemPromotionCreativeName' => [
                'apiName' => 'itemPromotionCreativeName',
                'uiName' => 'Item promotion creative name',
                'category' => 'Ecommerce',
                'description' => 'The name of the item-promotion creative.',
                'isCustomDefinition' => false,
            ],
            'itemPromotionId' => [
                'apiName' => 'itemPromotionId',
                'uiName' => 'Item promotion ID',
                'category' => 'Ecommerce',
                'description' => 'The ID of the item promotion.',
                'isCustomDefinition' => false,
            ],
            'itemPromotionName' => [
                'apiName' => 'itemPromotionName',
                'uiName' => 'Item promotion name',
                'category' => 'Ecommerce',
                'description' => 'The name of the promotion for the item.',
                'isCustomDefinition' => false,
            ],
            'landingPage' => [
                'apiName' => 'landingPage',
                'uiName' => 'Landing page',
                'category' => 'Other',
                'description' => 'The page path + query string associated with the first pageview in a session.',
                'isCustomDefinition' => false,
            ],
            'language' => [
                'apiName' => 'language',
                'uiName' => 'Language',
                'category' => 'Platform / Device',
                'description' => 'The language setting of the user\'s browser or device. e.g. English',
                'isCustomDefinition' => false,
            ],
            'languageCode' => [
                'apiName' => 'languageCode',
                'uiName' => 'Language code',
                'category' => 'Platform / Device',
                'description' => 'The language setting (ISO 639) of the user\'s browser or device. e.g. \'en-us\'',
                'isCustomDefinition' => false,
            ],
            'linkClasses' => [
                'apiName' => 'linkClasses',
                'uiName' => 'Link classes',
                'category' => 'Other',
                'description' => 'The HTML class attribute for an outbound link. For example if a user clicks a link \'<a class="center" href="www.youtube.com">\', this dimension will return \'center\'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'link_classes\'.',
                'isCustomDefinition' => false,
            ],
            'linkDomain' => [
                'apiName' => 'linkDomain',
                'uiName' => 'Link domain',
                'category' => 'Other',
                'description' => 'The destination domain of the outbound link. For example if a user clicks a link \'<a href="www.youtube.com">\', this dimension will return \'youtube.com\'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'link_domain\'.',
                'isCustomDefinition' => false,
            ],
            'linkId' => [
                'apiName' => 'linkId',
                'uiName' => 'Link ID',
                'category' => 'Other',
                'description' => 'The HTML id attribute for an outbound link or file download. For example if a user clicks a link \'<a id="socialLinks" href="www.youtube.com">\', this dimension will return \'socialLinks\'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'link_id\'.',
                'isCustomDefinition' => false,
            ],
            'linkText' => [
                'apiName' => 'linkText',
                'uiName' => 'Link text',
                'category' => 'Other',
                'description' => 'The link text of the file download. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'link_text\'.',
                'isCustomDefinition' => false,
            ],
            'linkUrl' => [
                'apiName' => 'linkUrl',
                'uiName' => 'Link URL',
                'category' => 'Other',
                'description' => 'The full url for an outbound link or file download. For example if a user clicks a link \'<a href="https://www.youtube.com/results?search_query=analytics">\', this dimension will return \'https://www.youtube.com/results?search_query=analytics\'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'link_url\'.',
                'isCustomDefinition' => false,
            ],
            'manualAdContent' => [
                'apiName' => 'manualAdContent',
                'uiName' => 'Manual ad content',
                'category' => 'Attribution',
                'description' => 'The ad content attributed to the conversion event. Populated by the utm_content parameter.',
                'isCustomDefinition' => false,
            ],
            'manualTerm' => [
                'apiName' => 'manualTerm',
                'uiName' => 'Manual term',
                'category' => 'Attribution',
                'description' => 'The term attributed to the conversion event. Populated by the utm_term parameter.',
                'isCustomDefinition' => false,
            ],
            'medium' => [
                'apiName' => 'medium',
                'uiName' => 'Medium',
                'category' => 'Attribution',
                'description' => 'The medium attributed to the conversion event.',
                'isCustomDefinition' => false,
            ],
            'method' => [
                'apiName' => 'method',
                'uiName' => 'Method',
                'category' => 'Other',
                'description' => 'The method by which an event was triggered. Populated by the event parameter \'method\'.',
                'isCustomDefinition' => false,
            ],
            'minute' => [
                'apiName' => 'minute',
                'uiName' => 'Minute',
                'category' => 'Time',
                'description' => 'The two-digit minute of the hour that the event was logged. This dimension ranges from 0-59 and is reported in your property\'s timezone.',
                'isCustomDefinition' => false,
            ],
            'mobileDeviceBranding' => [
                'apiName' => 'mobileDeviceBranding',
                'uiName' => 'Device brand',
                'category' => 'Platform / Device',
                'description' => 'Manufacturer or branded name (examples: Samsung, HTC, Verizon, T-Mobile).',
                'isCustomDefinition' => false,
            ],
            'mobileDeviceMarketingName' => [
                'apiName' => 'mobileDeviceMarketingName',
                'uiName' => 'Device',
                'category' => 'Platform / Device',
                'description' => 'The branded device name (examples: Galaxy S10 or P30 Pro).',
                'isCustomDefinition' => false,
            ],
            'mobileDeviceModel' => [
                'apiName' => 'mobileDeviceModel',
                'uiName' => 'Mobile model',
                'category' => 'Platform / Device',
                'description' => 'The mobile device model name (examples: iPhone X or SM-G950F).',
                'isCustomDefinition' => false,
            ],
            'month' => [
                'apiName' => 'month',
                'uiName' => 'Month',
                'category' => 'Time',
                'description' => 'The month of the event, a two digit integer from 01 to 12.',
                'isCustomDefinition' => false,
            ],
            'newVsReturning' => [
                'apiName' => 'newVsReturning',
                'uiName' => 'New / returning',
                'category' => 'User',
                'description' => 'New users have 0 previous sessions, and returning users have 1 or more previous sessions. This dimension returns two values: \'new\' or \'returning\'.',
                'isCustomDefinition' => false,
            ],
            'nthDay' => [
                'apiName' => 'nthDay',
                'uiName' => 'Nth day',
                'category' => 'Time',
                'description' => 'The number of days since the start of the date range.',
                'isCustomDefinition' => false,
            ],
            'nthHour' => [
                'apiName' => 'nthHour',
                'uiName' => 'Nth hour',
                'category' => 'Time',
                'description' => 'The number of hours since the start of the date range. The starting hour is 0000.',
                'isCustomDefinition' => false,
            ],
            'nthMinute' => [
                'apiName' => 'nthMinute',
                'uiName' => 'Nth minute',
                'category' => 'Time',
                'description' => 'The number of minutes since the start of the date range. The starting minute is 0000.',
                'isCustomDefinition' => false,
            ],
            'nthMonth' => [
                'apiName' => 'nthMonth',
                'uiName' => 'Nth month',
                'category' => 'Time',
                'description' => 'The number of months since the start of a date range. The starting month is 0000.',
                'isCustomDefinition' => false,
            ],
            'nthWeek' => [
                'apiName' => 'nthWeek',
                'uiName' => 'Nth week',
                'category' => 'Time',
                'description' => 'A number representing the number of weeks since the start of a date range.',
                'isCustomDefinition' => false,
            ],
            'nthYear' => [
                'apiName' => 'nthYear',
                'uiName' => 'Nth year',
                'category' => 'Time',
                'description' => 'The number of years since the start of the date range. The starting year is 0000.',
                'isCustomDefinition' => false,
            ],
            'operatingSystem' => [
                'apiName' => 'operatingSystem',
                'uiName' => 'Operating system',
                'category' => 'Platform / Device',
                'description' => 'The operating systems used by visitors to your app or website. Includes desktop and mobile operating systems such as Windows and Android.',
                'isCustomDefinition' => false,
            ],
            'operatingSystemVersion' => [
                'apiName' => 'operatingSystemVersion',
                'uiName' => 'OS version',
                'category' => 'Platform / Device',
                'description' => 'The operating system versions used by visitors to your website or app. For example, Android 10\'s version is 10, and iOS 13.5.1\'s version is 13.5.1.',
                'isCustomDefinition' => false,
            ],
            'operatingSystemWithVersion' => [
                'apiName' => 'operatingSystemWithVersion',
                'uiName' => 'Operating system with version',
                'category' => 'Platform / Device',
                'description' => 'The operating system and version. For example, Android 10 or Windows 7.',
                'isCustomDefinition' => false,
            ],
            'orderCoupon' => [
                'apiName' => 'orderCoupon',
                'uiName' => 'Order coupon',
                'category' => 'Ecommerce',
                'description' => 'Code for the order-level coupon.',
                'isCustomDefinition' => false,
            ],
            'outbound' => [
                'apiName' => 'outbound',
                'uiName' => 'Outbound',
                'category' => 'Other',
                'description' => 'Returns \'true\' if the link lead to a site is not a part of the property’s domain. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'outbound\'.',
                'isCustomDefinition' => false,
            ],
            'pageLocation' => [
                'apiName' => 'pageLocation',
                'uiName' => 'Page location',
                'category' => 'Page / Screen',
                'description' => 'The protocol, hostname, page path, and query string for web pages visited; for example, the pageLocation portion of https://www.example.com/store/contact-us?query_string=true is https://www.example.com/store/contact-us?query_string=true. Populated by the event parameter \'page_location\'.',
                'isCustomDefinition' => false,
            ],
            'pagePath' => [
                'apiName' => 'pagePath',
                'uiName' => 'Page path',
                'category' => 'Page / Screen',
                'description' => 'The portion of the URL between the hostname and query string for web pages visited; for example, the pagePath portion of https://www.example.com/store/contact-us?query_string=true is /store/contact-us.',
                'isCustomDefinition' => false,
            ],
            'pagePathPlusQueryString' => [
                'apiName' => 'pagePathPlusQueryString',
                'uiName' => 'Page path + query string',
                'category' => 'Page / Screen',
                'description' => 'The portion of the URL following the hostname for web pages visited; for example, the pagePathPlusQueryString portion of https://www.example.com/store/contact-us?query_string=true is /store/contact-us?query_string=true.',
                'isCustomDefinition' => false,
            ],
            'pageReferrer' => [
                'apiName' => 'pageReferrer',
                'uiName' => 'Page referrer',
                'category' => 'Page / Screen',
                'description' => 'The full referring URL including the hostname and path. This referring URL is the user\'s previous URL and can be this website\'s domain or other domains. Populated by the event parameter \'page_referrer\'.',
                'isCustomDefinition' => false,
            ],
            'pageTitle' => [
                'apiName' => 'pageTitle',
                'uiName' => 'Page title',
                'category' => 'Page / Screen',
                'description' => 'The web page titles used on your site.',
                'isCustomDefinition' => false,
            ],
            'percentScrolled' => [
                'apiName' => 'percentScrolled',
                'uiName' => 'Percent scrolled',
                'category' => 'Other',
                'description' => 'The percentage down the page that the user has scrolled (for example, \'90\'). Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'percent_scrolled\'.',
                'isCustomDefinition' => false,
            ],
            'platform' => [
                'apiName' => 'platform',
                'uiName' => 'Platform',
                'category' => 'Platform / Device',
                'description' => 'The platform on which your app or website ran; for example, web, iOS, or Android. To determine a stream\'s type in a report, use both platform and streamId.',
                'isCustomDefinition' => false,
            ],
            'platformDeviceCategory' => [
                'apiName' => 'platformDeviceCategory',
                'uiName' => 'Platform / device category',
                'category' => 'Platform / Device',
                'description' => 'The platform and type of device on which your website or mobile app ran. (example: Android / mobile)',
                'isCustomDefinition' => false,
            ],
            'region' => [
                'apiName' => 'region',
                'uiName' => 'Region',
                'category' => 'Geography',
                'description' => 'The geographic region from which the user activity originated, derived from their IP address.',
                'isCustomDefinition' => false,
            ],
            'screenResolution' => [
                'apiName' => 'screenResolution',
                'uiName' => 'Screen resolution',
                'category' => 'Platform / Device',
                'description' => 'The screen resolution of the user\'s monitor. For example, 1920x1080.',
                'isCustomDefinition' => false,
            ],
            'searchTerm' => [
                'apiName' => 'searchTerm',
                'uiName' => 'Search term',
                'category' => 'Other',
                'description' => 'The term searched by the user. For example if the user visits \'/some-page.html?q=some-term\', this dimension returns \'some-term\'. Automatically populated if Enhanced Measurement is enabled. Populated by the event parameter \'search_term\'.',
                'isCustomDefinition' => false,
            ],
            'sessionCampaignId' => [
                'apiName' => 'sessionCampaignId',
                'uiName' => 'Session campaign ID',
                'category' => 'Traffic Source',
                'description' => 'The marketing campaign id for a session. Includes Google Ads Campaigns.',
                'isCustomDefinition' => false,
            ],
            'sessionCampaignName' => [
                'apiName' => 'sessionCampaignName',
                'uiName' => 'Session campaign',
                'category' => 'Traffic Source',
                'description' => 'The marketing campaign name for a session. Includes Google Ads and Manual Campaigns.',
                'isCustomDefinition' => false,
            ],
            'sessionDefaultChannelGrouping' => [
                'apiName' => 'sessionDefaultChannelGrouping',
                'uiName' => 'Session default channel grouping',
                'category' => 'Traffic Source',
                'description' => 'The session\'s default channel grouping is based primarily on source and medium. An enumeration which includes \'Direct\', \'Organic Search\', \'Paid Social\', \'Organic Social\', \'Email\', \'Affiliates\', \'Referral\', \'Paid Search\', \'Video\', and \'Display\'.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsAccountName' => [
                'apiName' => 'sessionGoogleAdsAccountName',
                'uiName' => 'Session Google Ads account name',
                'category' => 'Traffic Source',
                'description' => 'A customer\'s descriptive name in Google Ads. Corresponding to customer.descriptive_name in the Google Ads API.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsAdGroupId' => [
                'apiName' => 'sessionGoogleAdsAdGroupId',
                'uiName' => 'Session Google Ads ad group ID',
                'category' => 'Traffic Source',
                'description' => 'The Ad Group Id in Google Ads for a session.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsAdGroupName' => [
                'apiName' => 'sessionGoogleAdsAdGroupName',
                'uiName' => 'Session Google Ads ad group name',
                'category' => 'Traffic Source',
                'description' => 'The Ad Group Name in Google Ads for a session.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsAdNetworkType' => [
                'apiName' => 'sessionGoogleAdsAdNetworkType',
                'uiName' => 'Session Google Ads ad network type',
                'category' => 'Traffic Source',
                'description' => 'The advertising network that led to the session. An enumeration which includes \'Google search\', \'Search partners\', \'Google Display Network\', \'Youtube Search\', \'Youtube Videos\', \'Cross-network\', \'Social\', and \'(universal campaign)\'.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsCampaignType' => [
                'apiName' => 'sessionGoogleAdsCampaignType',
                'uiName' => 'Session Google Ads campaign type',
                'category' => 'Traffic Source',
                'description' => 'The campaign type for the Google Ads campaign that led to this session. Campaign types determine where customers see your ads and the settings and options available to you in Google Ads. Campaign type is an enumeration that includes: Search, Display, Shopping, Video, Discovery, App, Smart, Hotel, Local, and Performance Max. To learn more, see https://support.google.com/google-ads/answer/2567043.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsCreativeId' => [
                'apiName' => 'sessionGoogleAdsCreativeId',
                'uiName' => 'Session Google Ads creative ID',
                'category' => 'Traffic Source',
                'description' => 'The ID of the Google Ads creative that lead to a session on your website or app. Creative IDs identify individual ads.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsKeyword' => [
                'apiName' => 'sessionGoogleAdsKeyword',
                'uiName' => 'Session Google Ads keyword text',
                'category' => 'Traffic Source',
                'description' => 'The matched keyword that led to the session. Keywords are words or phrases describing your product or service that you choose to get your ad in front of the right customers. To learn more about Keywords, see <https://support.google.com/google-ads/answer/6323>.',
                'isCustomDefinition' => false,
            ],
            'sessionGoogleAdsQuery' => [
                'apiName' => 'sessionGoogleAdsQuery',
                'uiName' => 'Session Google Ads query',
                'category' => 'Traffic Source',
                'description' => 'The search query that led to the session.',
                'isCustomDefinition' => false,
            ],
            'sessionManualAdContent' => [
                'apiName' => 'sessionManualAdContent',
                'uiName' => 'Session manual ad content',
                'category' => 'Traffic Source',
                'description' => 'The ad content that led to a session. Populated by the utm_content parameter.',
                'isCustomDefinition' => false,
            ],
            'sessionManualTerm' => [
                'apiName' => 'sessionManualTerm',
                'uiName' => 'Session manual term',
                'category' => 'Traffic Source',
                'description' => 'The term that led to a session. Populated by the utm_term parameter.',
                'isCustomDefinition' => false,
            ],
            'sessionMedium' => [
                'apiName' => 'sessionMedium',
                'uiName' => 'Session medium',
                'category' => 'Traffic Source',
                'description' => 'The medium that initiated a session on your website or app.',
                'isCustomDefinition' => false,
            ],
            'sessionSource' => [
                'apiName' => 'sessionSource',
                'uiName' => 'Session source',
                'category' => 'Traffic Source',
                'description' => 'The source that initiated a session on your website or app.',
                'isCustomDefinition' => false,
            ],
            'sessionSourcePlatform' => [
                'apiName' => 'sessionSourcePlatform',
                'uiName' => 'Session source platform',
                'category' => 'Traffic Source',
                'description' => 'The source platform of the session\'s campaign. Please do not depend on this field returning \'Manual\' for traffic that uses UTMs; this field will update from returning \'Manual\' to returning \'(not set)\' for an upcoming feature launch.',
                'isCustomDefinition' => false,
            ],
            'signedInWithUserId' => [
                'apiName' => 'signedInWithUserId',
                'uiName' => 'Signed in with user ID',
                'category' => 'User',
                'description' => 'The string \'yes\' if the user signed in with the User-ID feature. To learn more about User-ID, see <https://support.google.com/analytics/answer/9213390>.',
                'isCustomDefinition' => false,
            ],
            'source' => [
                'apiName' => 'source',
                'uiName' => 'Source',
                'category' => 'Attribution',
                'description' => 'The source attributed to the conversion event.',
                'isCustomDefinition' => false,
            ],
            'sourcePlatform' => [
                'apiName' => 'sourcePlatform',
                'uiName' => 'Source platform',
                'category' => 'Attribution',
                'description' => 'The source platform of the conversion event\'s campaign. Please do not depend on this field returning \'Manual\' for traffic that uses UTMs; this field will update from returning \'Manual\' to returning \'(not set)\' for an upcoming feature launch.',
                'isCustomDefinition' => false,
            ],
            'streamId' => [
                'apiName' => 'streamId',
                'uiName' => 'Stream ID',
                'category' => 'Platform / Device',
                'description' => 'The numeric data stream identifier for your app or website.',
                'isCustomDefinition' => false,
            ],
            'streamName' => [
                'apiName' => 'streamName',
                'uiName' => 'Stream name',
                'category' => 'Platform / Device',
                'description' => 'The data stream name for your app or website.',
                'isCustomDefinition' => false,
            ],
            'testDataFilterName' => [
                'apiName' => 'testDataFilterName',
                'uiName' => 'Test data filter name',
                'category' => 'Other',
                'description' => 'The name of data filters in testing state. You use data filters to include or exclude event data from your reports based on event-parameter values. To learn more, see <https://support.google.com/analytics/answer/10108813>.',
                'isCustomDefinition' => false,
            ],
            'transactionId' => [
                'apiName' => 'transactionId',
                'uiName' => 'Transaction ID',
                'category' => 'Ecommerce',
                'description' => 'The ID of the ecommerce transaction.',
                'isCustomDefinition' => false,
            ],
            'unifiedPagePathScreen' => [
                'apiName' => 'unifiedPagePathScreen',
                'uiName' => 'Page path and screen class',
                'category' => 'Page / Screen',
                'description' => 'The page path (web) or screen class (app) on which the event was logged.',
                'isCustomDefinition' => false,
            ],
            'unifiedPageScreen' => [
                'apiName' => 'unifiedPageScreen',
                'uiName' => 'Page path + query string and screen class',
                'category' => 'Page / Screen',
                'description' => 'The page path and query string (web) or screen class (app) on which the event was logged.',
                'isCustomDefinition' => false,
            ],
            'unifiedScreenClass' => [
                'apiName' => 'unifiedScreenClass',
                'uiName' => 'Page title and screen class',
                'category' => 'Page / Screen',
                'description' => 'The page title (web) or screen class (app) on which the event was logged.',
                'isCustomDefinition' => false,
            ],
            'unifiedScreenName' => [
                'apiName' => 'unifiedScreenName',
                'uiName' => 'Page title and screen name',
                'category' => 'Page / Screen',
                'description' => 'The page title (web) or screen name (app) on which the event was logged.',
                'isCustomDefinition' => false,
            ],
            'userAgeBracket' => [
                'apiName' => 'userAgeBracket',
                'uiName' => 'Age',
                'category' => 'Demographics',
                'description' => 'User age brackets.',
                'isCustomDefinition' => false,
            ],
            'userGender' => [
                'apiName' => 'userGender',
                'uiName' => 'Gender',
                'category' => 'Demographics',
                'description' => 'User gender.',
                'isCustomDefinition' => false,
            ],
            'videoProvider' => [
                'apiName' => 'videoProvider',
                'uiName' => 'Video provider',
                'category' => 'Other',
                'description' => 'The source of the video (for example, \'youtube\'). Automatically populated for embedded videos if Enhanced Measurement is enabled. Populated by the event parameter \'video_provider\'.',
                'isCustomDefinition' => false,
            ],
            'videoTitle' => [
                'apiName' => 'videoTitle',
                'uiName' => 'Video title',
                'category' => 'Other',
                'description' => 'The title of the video. Automatically populated for embedded videos if Enhanced Measurement is enabled. Populated by the event parameter \'video_title\'.',
                'isCustomDefinition' => false,
            ],
            'videoUrl' => [
                'apiName' => 'videoUrl',
                'uiName' => 'Video URL',
                'category' => 'Other',
                'description' => 'The url of the video. Automatically populated for embedded videos if Enhanced Measurement is enabled. Populated by the event parameter \'video_url\'.',
                'isCustomDefinition' => false,
            ],
            'visible' => [
                'apiName' => 'visible',
                'uiName' => 'Visible',
                'category' => 'Other',
                'description' => 'Returns \'true\' if the content is visible. Automatically populated for embedded videos if Enhanced Measurement is enabled. Populated by the event parameter \'visible\'.',
                'isCustomDefinition' => false,
            ],
            'week' => [
                'apiName' => 'week',
                'uiName' => 'Week',
                'category' => 'Time',
                'description' => 'The week of the event, a two-digit number from 01 to 53. Each week starts on Sunday. January 1st is always in week 01. The first and last week of the year have fewer than 7 days in most years. Weeks other than the first and the last week of the year always have 7 days. For years where January 1st is a Sunday, the first week of that year and the last week of the prior year have 7 days.',
                'isCustomDefinition' => false,
            ],
            'year' => [
                'apiName' => 'year',
                'uiName' => 'Year',
                'category' => 'Time',
                'description' => 'The four-digit year of the event e.g. 2020.',
                'isCustomDefinition' => false,
            ],
        ];
    }
}
