<?php

class CAnalytics_Google_MetaData_Metrics {
    public static function all() {
        return [
            'active1DayUsers' => [
                'apiName' => 'active1DayUsers',
                'uiName' => '1-day active users',
                'category' => 'User',
                'description' => 'The number of distinct active users on your site or app within a 1 day period. The 1 day period includes the last day in the report\'s date range. Note: this is the same as Active Users.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'active28DayUsers' => [
                'apiName' => 'active28DayUsers',
                'uiName' => '28-day active users',
                'category' => 'User',
                'description' => 'The number of distinct active users on your site or app within a 28 day period. The 28 day period includes the last day in the report\'s date range.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'active7DayUsers' => [
                'apiName' => 'active7DayUsers',
                'uiName' => '7-day active users',
                'category' => 'User',
                'description' => 'The number of distinct active users on your site or app within a 7 day period. The 7 day period includes the last day in the report\'s date range.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'activeUsers' => [
                'apiName' => 'activeUsers',
                'uiName' => 'Active users',
                'category' => 'User',
                'description' => 'The number of distinct users who visited your site or app.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'addToCarts' => [
                'apiName' => 'addToCarts',
                'uiName' => 'Add-to-carts',
                'category' => 'Ecommerce',
                'description' => 'The number of times users added items to their shopping carts.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'adUnitExposure' => [
                'apiName' => 'adUnitExposure',
                'uiName' => 'Ad unit exposure',
                'category' => 'Publisher',
                'description' => 'The time that an ad unit was exposed to a user, in milliseconds.',
                'isCustomDefinition' => false,
                'type' => 5,
                'typeName' => 'TYPE_MILLISECONDS',
            ],
            'averagePurchaseRevenue' => [
                'apiName' => 'averagePurchaseRevenue',
                'uiName' => 'Average purchase revenue',
                'category' => 'Revenue',
                'description' => 'The average purchase revenue in the transaction group of events.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'averagePurchaseRevenuePerPayingUser' => [
                'apiName' => 'averagePurchaseRevenuePerPayingUser',
                'uiName' => 'ARPPU',
                'category' => 'Revenue',
                'description' => 'Average revenue per paying user (ARPPU) is the total purchase revenue per active user that logged a purchase event. The summary metric is for the time period selected.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'averagePurchaseRevenuePerUser' => [
                'apiName' => 'averagePurchaseRevenuePerUser',
                'uiName' => 'Average purchase revenue per user',
                'category' => 'Revenue',
                'description' => 'The average purchase revenue per active user is the total purchase revenue per active user that logged any event. The summary metric is for the time period selected.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'averageRevenuePerUser' => [
                'apiName' => 'averageRevenuePerUser',
                'uiName' => 'ARPU',
                'category' => 'Revenue',
                'description' => 'Average revenue per active user (ARPU). The summary metric is for the time period selected. ARPU uses Total Revenue and includes AdMob estimated earnings.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'averageSessionDuration' => [
                'apiName' => 'averageSessionDuration',
                'uiName' => 'Average session duration',
                'category' => 'Session',
                'description' => 'The average duration (in seconds) of users\' sessions.',
                'isCustomDefinition' => false,
                'type' => 4,
                'typeName' => 'TYPE_SECONDS',
            ],
            'cartToViewRate' => [
                'apiName' => 'cartToViewRate',
                'uiName' => 'Cart-to-view rate',
                'category' => 'Other',
                'description' => 'The number of users who added a product(s) to their cart divided by the number of users who viewed the same product(s). This metric is returned as a fraction; for example, 0.1132 means 11.32% of users who viewed a product also added the same product to their cart.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'checkouts' => [
                'apiName' => 'checkouts',
                'uiName' => 'Checkouts',
                'category' => 'Ecommerce',
                'description' => 'The number of times users started the checkout process.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'cohortActiveUsers' => [
                'apiName' => 'cohortActiveUsers',
                'uiName' => 'Cohort active users',
                'category' => 'Cohort',
                'description' => 'The number of users in the cohort who are active in the time window corresponding to the cohort nth day/week/month. For example for the row where cohortNthWeek = 0001, this metric is the number of users (in the cohort) who are active in week 1.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'cohortTotalUsers' => [
                'apiName' => 'cohortTotalUsers',
                'uiName' => 'Cohort total users',
                'category' => 'Cohort',
                'description' => 'The total number of users in the cohort. This metric is the same value in every row of the report for each cohort. Because cohorts are defined by a shared acquisition date, cohortTotalUsers is the same as cohortActiveUsers for the cohort\'s selection date range. For report rows later than the ochort\'s selection range, it is typical for cohortActiveUsers to be smaller than cohortTotalUsers. This difference represents users from the cohort that were not active for the later date. cohortTotalUsers is commonly used in the metric expression cohortActiveUsers/cohortTotalUsers to compute a user retention fraction for the cohort. The relationship between activeUsers and totalUsers is not equivalent to the relationship between cohortActiveUsers and cohortTotalUsers.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'conversions' => [
                'apiName' => 'conversions',
                'uiName' => 'Conversions',
                'category' => 'Event',
                'description' => 'The count of conversion events. Events are marked as conversions at collection time; changes to an event\'s conversion marking apply going forward. You can mark any event as a conversion in Google Analytics, and some events (i.e. first_open, purchase) are marked as conversions by default. To learn more, see <https://support.google.com/analytics/answer/9267568>.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'crashAffectedUsers' => [
                'apiName' => 'crashAffectedUsers',
                'uiName' => 'Crash-affected users',
                'category' => 'Other',
                'description' => 'The number of users that logged a crash in this row of the report. For example if the report is time series by date, this metrics reports total users with at least one crash on this date. Crashes are events with the name "app_exception".',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'crashFreeUsersRate' => [
                'apiName' => 'crashFreeUsersRate',
                'uiName' => 'Crash-free users rate',
                'category' => 'Other',
                'description' => 'The number of users without crash events (in this row of the report) divided by the total number of users. This metric is returned as a fraction; for example, 0.9243 means 92.43% of users were crash-free.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'dauPerMau' => [
                'apiName' => 'dauPerMau',
                'uiName' => 'DAU / MAU',
                'category' => 'User',
                'description' => 'The rolling percent of 30-day active users who are also 1-day active users. This metric is returned as a fraction; for example, 0.113 means 11.3% of 30-day active users were also 1-day active users.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'dauPerWau' => [
                'apiName' => 'dauPerWau',
                'uiName' => 'DAU / WAU',
                'category' => 'User',
                'description' => 'The rolling percent of 7-day active users who are also 1-day active users. This metric is returned as a fraction; for example, 0.082 means 8.2% of 7-day active users were also 1-day active users.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'ecommercePurchases' => [
                'apiName' => 'ecommercePurchases',
                'uiName' => 'Ecommerce purchases',
                'category' => 'Ecommerce',
                'description' => 'The number of times users completed a purchase. This metric counts \'purchase\' events; this metric does not count \'in_app_purchase\' and subscription events.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'engagedSessions' => [
                'apiName' => 'engagedSessions',
                'uiName' => 'Engaged sessions',
                'category' => 'Session',
                'description' => 'The number of sessions that lasted longer than 10 seconds, or had a conversion event, or had 2 or more screen views.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'engagementRate' => [
                'apiName' => 'engagementRate',
                'uiName' => 'Engagement rate',
                'category' => 'Session',
                'description' => 'The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction; for example, 0.7239 means 72.39% of sessions were engaged sessions.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'eventCount' => [
                'apiName' => 'eventCount',
                'uiName' => 'Event count',
                'category' => 'Event',
                'description' => 'The count of events.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'eventCountPerUser' => [
                'apiName' => 'eventCountPerUser',
                'uiName' => 'Event count per user',
                'category' => 'Event',
                'description' => 'The average number of events per user (Event count divided by Active users).',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'eventsPerSession' => [
                'apiName' => 'eventsPerSession',
                'uiName' => 'Events per session',
                'category' => 'Event',
                'description' => 'The average number of events per session (Event count divided by Sessions).',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'eventValue' => [
                'apiName' => 'eventValue',
                'uiName' => 'Event value',
                'category' => 'Event',
                'description' => 'The sum of the event parameter named \'value\'.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'firstTimePurchaserConversionRate' => [
                'apiName' => 'firstTimePurchaserConversionRate',
                'uiName' => 'First-time purchaser conversion',
                'category' => 'User',
                'description' => 'The percentage of active users who made their first purchase. This metric is returned as a fraction; for example, 0.092 means 9.2% of active users were first time purchasers.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'firstTimePurchasers' => [
                'apiName' => 'firstTimePurchasers',
                'uiName' => 'First time purchasers',
                'category' => 'User',
                'description' => 'The number of users that completed their first purchase event.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'firstTimePurchasersPerNewUser' => [
                'apiName' => 'firstTimePurchasersPerNewUser',
                'uiName' => 'First-time purchasers per new user',
                'category' => 'User',
                'description' => 'The average number of first time purchasers per new user.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'itemListClicks' => [
                'apiName' => 'itemListClicks',
                'uiName' => 'Item list clicks',
                'category' => 'Ecommerce',
                'description' => 'The number of times users clicked an item when it appeared in a list.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'itemListClickThroughRate' => [
                'apiName' => 'itemListClickThroughRate',
                'uiName' => 'Item list click through rate',
                'category' => 'Ecommerce',
                'description' => 'The number of users who selected a list(s) divided by the number of users who viewed the same list(s). This metric is returned as a fraction; for example, 0.2145 means 21.45% of users who viewed a list also selected the same list.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'itemListViews' => [
                'apiName' => 'itemListViews',
                'uiName' => 'Item list views',
                'category' => 'Ecommerce',
                'description' => 'The number of times the item list was viewed.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'itemPromotionClicks' => [
                'apiName' => 'itemPromotionClicks',
                'uiName' => 'Item promotion clicks',
                'category' => 'Ecommerce',
                'description' => 'The number of times an item promotion was clicked.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'itemPromotionClickThroughRate' => [
                'apiName' => 'itemPromotionClickThroughRate',
                'uiName' => 'Item promotion click through rate',
                'category' => 'Ecommerce',
                'description' => 'The number of users who selected a promotion(s) divided by the number of users who viewed the same promotion(s). This metric is returned as a fraction; for example, 0.1382 means 13.82% of users who viewed a promotion also selected the promotion.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'itemPromotionViews' => [
                'apiName' => 'itemPromotionViews',
                'uiName' => 'Item promotion views',
                'category' => 'Ecommerce',
                'description' => 'The number of times an item promotion was viewed.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'itemPurchaseQuantity' => [
                'apiName' => 'itemPurchaseQuantity',
                'uiName' => 'Item purchase quantity',
                'category' => 'Ecommerce',
                'description' => 'The number of units for a single item included in purchase events.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'itemRevenue' => [
                'apiName' => 'itemRevenue',
                'uiName' => 'Item revenue',
                'category' => 'Ecommerce',
                'description' => 'The total revenue from items only. Item revenue is the product of its price and quantity. Item revenue excludes tax and shipping values.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'itemViews' => [
                'apiName' => 'itemViews',
                'uiName' => 'Item views',
                'category' => 'Ecommerce',
                'description' => 'The number of times the item details were viewed.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'newUsers' => [
                'apiName' => 'newUsers',
                'uiName' => 'New users',
                'category' => 'User',
                'description' => 'The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'publisherAdClicks' => [
                'apiName' => 'publisherAdClicks',
                'uiName' => 'Publisher ad clicks',
                'category' => 'Other',
                'description' => 'The number of ad_click events.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'publisherAdImpressions' => [
                'apiName' => 'publisherAdImpressions',
                'uiName' => 'Publisher ad impressions',
                'category' => 'Other',
                'description' => 'The number of ad_impression events.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'purchaserConversionRate' => [
                'apiName' => 'purchaserConversionRate',
                'uiName' => 'Purchaser conversion',
                'category' => 'Other',
                'description' => 'The percentage of active users who made 1 or more purchase transactions. This metric is returned as a fraction; for example, 0.412 means 41.2% of users were purchasers.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'purchaseRevenue' => [
                'apiName' => 'purchaseRevenue',
                'uiName' => 'Purchase revenue',
                'category' => 'Ecommerce',
                'description' => 'The sum of revenue from purchases made in your app or site. Purchase revenue sums the revenue for these events: purchase, ecommerce_purchase, in_app_purchase, app_store_subscription_convert, and app_store_subscription_renew.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'purchaseToViewRate' => [
                'apiName' => 'purchaseToViewRate',
                'uiName' => 'Purchase-to-view rate',
                'category' => 'Other',
                'description' => 'The number of users who purchased a product(s) divided by the number of users who viewed the same product(s). This metric is returned as a fraction; for example, 0.128 means 12.8% of users that viewed a product(s) also purchased the same product(s).',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'screenPageViews' => [
                'apiName' => 'screenPageViews',
                'uiName' => 'Views',
                'category' => 'Page / Screen',
                'description' => 'The number of app screens or web pages your users viewed. Repeated views of a single page or screen are counted. (screen_view + page_view events).',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'screenPageViewsPerSession' => [
                'apiName' => 'screenPageViewsPerSession',
                'uiName' => 'Views per session',
                'category' => 'Page / Screen',
                'description' => 'The number of app screens or web pages your users viewed per session. Repeated views of a single page or screen are counted. (screen_view + page_view events) / sessions.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'sessions' => [
                'apiName' => 'sessions',
                'uiName' => 'Sessions',
                'category' => 'Session',
                'description' => 'The number of sessions that began on your site or app (event triggered: session_start).',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'sessionsPerUser' => [
                'apiName' => 'sessionsPerUser',
                'uiName' => 'Sessions per user',
                'category' => 'Session',
                'description' => 'The average number of sessions per user (Sessions divided by Active Users).',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
            'totalAdRevenue' => [
                'apiName' => 'totalAdRevenue',
                'uiName' => 'Total ad revenue',
                'category' => 'Other',
                'description' => 'The total advertising revenue from both Admob and third-party sources.',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'totalPurchasers' => [
                'apiName' => 'totalPurchasers',
                'uiName' => 'Total purchasers',
                'category' => 'User',
                'description' => 'The number of users that logged purchase events for the time period selected.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'totalRevenue' => [
                'apiName' => 'totalRevenue',
                'uiName' => 'Total revenue',
                'category' => 'Revenue',
                'description' => 'The sum of revenue from purchases, subscriptions, and advertising (Purchase revenue plus Subscription revenue plus Ad revenue).',
                'isCustomDefinition' => false,
                'type' => 9,
                'typeName' => 'TYPE_CURRENCY',
            ],
            'totalUsers' => [
                'apiName' => 'totalUsers',
                'uiName' => 'Total users',
                'category' => 'User',
                'description' => 'The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'transactions' => [
                'apiName' => 'transactions',
                'uiName' => 'Transactions',
                'category' => 'Ecommerce',
                'description' => 'The count of transaction events with purchase revenue. Transaction events are in_app_purchase, ecommerce_purchase, purchase, app_store_subscription_renew, app_store_subscription_convert, and refund.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'transactionsPerPurchaser' => [
                'apiName' => 'transactionsPerPurchaser',
                'uiName' => 'Transactions per purchaser',
                'category' => 'Ecommerce',
                'description' => 'The average numer of transactions per purchaser.',
                'isCustomDefinition' => false,
                'type' => 1,
                'typeName' => 'TYPE_INTEGER',
            ],
            'userEngagementDuration' => [
                'apiName' => 'userEngagementDuration',
                'uiName' => 'User engagement',
                'category' => 'User',
                'description' => 'The total amount of time (in seconds) your website or app was in the foreground of users\' devices.',
                'isCustomDefinition' => false,
                'type' => 4,
                'typeName' => 'TYPE_SECONDS',
            ],
            'wauPerMau' => [
                'apiName' => 'wauPerMau',
                'uiName' => 'WAU / MAU',
                'category' => 'User',
                'description' => 'The rolling percent of 30-day active users who are also 7-day active users. This metric is returned as a fraction; for example, 0.234 means 23.4% of 30-day active users were also 7-day active users.',
                'isCustomDefinition' => false,
                'type' => 2,
                'typeName' => 'TYPE_FLOAT',
            ],
        ];
    }
}
