<?php

/**
 * Description of Variables.
 *
 * @author Hery
 *
 * @see CApp
 */
trait CApp_Concern_VariablesTrait {
    /**
     * @var array
     */
    protected static $variables = [];

    /**
     * Return all variables generated by CApp for used in js var capp.
     *
     * @return array
     */
    public static function variables() {
        /** @var CApp $this */
        $variables = [];
        $variables['decimal_separator'] = $variables['decimalSeparator'] = static::formatter()->getDecimalSeparator();
        $variables['thousand_separator'] = $variables['thousandSeparator'] = static::formatter()->getThousandSeparator();
        $variables['decimal_digit'] = $variables['decimalDigit'] = static::formatter()->getDecimalDigit();
        $cresjsConfig = CJavascript::cresJs()->getConfig();
        $variables['format'] = [];
        $variables['format']['decimalSeparator'] = static::formatter()->getDecimalSeparator();
        $variables['format']['thousandSeparator'] = static::formatter()->getThousandSeparator();
        $variables['format']['decimalDigit'] = static::formatter()->getDecimalDigit();
        $variables['format']['date'] = static::formatter()->getDateFormat();
        $variables['format']['datetime'] = static::formatter()->getDatetimeFormat();
        $variables['format']['currencyPrefix'] = static::formatter()->getCurrencyPrefix();
        $variables['format']['currencySuffix'] = static::formatter()->getCurrencySuffix();
        $variables['format']['currencyStripZeroDecimal'] = static::formatter()->getCurrencyStripZeroDecimal();
        $variables['format']['currencyDecimalDigit'] = static::formatter()->getCurrencyDecimalDigit();
        $variables['have_clock'] = $variables['haveClock'] = false;
        $variables['have_scroll_to_top'] = $variables['haveScrollToTop'] = carr::get($cresjsConfig, 'scroll_to_top');
        $variables['CFVersion'] = CF::version();
        $variables['domain'] = CF::domain();
        $variables['appCode'] = CF::appCode();
        $variables['appId'] = CF::appId();
        $variables['debug'] = CF::config('app.debug', false);
        $variables['environment'] = CF::environment();
        $variables['csrfToken'] = CSession::sessionConfigured() ? c::csrfToken() : null;
        $variables['vscode'] = [];
        $variables['vscode']['liveReload'] = carr::get($cresjsConfig, 'vscode.live_reload');
        $variables['react'] = [];
        $variables['react']['enable'] = carr::get($cresjsConfig, 'react.enable');
        $variables['block'] = [];
        $variables['block']['html'] = carr::get($cresjsConfig, 'block.html');
        $variables['waves'] = [];
        $variables['waves']['selector'] = carr::get($cresjsConfig, 'waves.selector');
        $variables['timezoneString'] = c::now()->format('P');
        $bootstrap = CF::config('app.bootstrap');
        $themeData = CManager::instance()->getThemeData();
        if (isset($themeData) && strlen(carr::get($themeData, 'bootstrap')) > 0) {
            $bootstrap = carr::get($themeData, 'bootstrap');
        }

        if (strlen($bootstrap) == 0) {
            $bootstrap = '2.3';
        }
        $variables['bootstrap'] = $bootstrap;

        $variables['base_url'] = curl::base();
        $variables['baseUrl'] = curl::base();
        $variables['sessionName'] = CF::config('session.name');
        $variables['label_confirm'] = c::__('Are you sure ?');
        $variables['labelConfirm'] = c::__('Are you sure ?');
        $variables['label_ok'] = c::__('OK');
        $variables['labelOk'] = c::__('OK');
        $variables['label_cancel'] = c::__('Cancel');
        $variables['labelCancel'] = c::__('Cancel');
        $variables['isAuthEnabled'] = c::app()->isAuthEnabled();
        $variables['alpine'] = carr::get($cresjsConfig, 'alpine');
        $labels = [
            'confirm' => [
                'areYouSure' => c::__('app.confirm:areYouSure'),
                'yes' => c::__('app.confirm:yes'),
                'no' => c::__('app.confirm:no'),
            ],
            'yes' => c::__('app.yes'),
            'no' => c::__('app.no'),
        ];
        $variables['labels'] = $labels;

        $asset = CManager::asset();
        $variables['requireJs'] = false;

        //we collect all client modules data
        $allModules = CManager::asset()->module()->allModules();
        $variables['modules'] = $allModules;
        $variables['theme'] = [];
        $variables['theme']['name'] = CManager::theme()->getCurrentTheme();
        $variables['theme']['data'] = CManager::theme()->getThemeData();

        $variables['jsUrl'] = CManager::asset()->getAllJsFileUrl();
        $variables['cssUrl'] = CManager::asset()->getAllCssFileUrl();

        $variables['defaultJQueryUrl'] = curl::base() . 'media/js/libs/jquery-3.3.1/jquery-3.3.1.min.js';

        if (is_array(static::$variables) && static::$variables) {
            $variables = array_merge($variables, static::$variables);
        }

        return $variables;
    }

    /**
     * Alias of variables.
     *
     * @return array
     *
     * @see CApp_Trait_App_Variables::variables()
     */
    public static function getVariables() {
        return static::variables();
    }

    /**
     * @param string $key
     * @param mixed  $value
     *
     * @return void
     */
    public static function setVariable($key, $value) {
        if (static::$variables == null) {
            static::$variables = [];
        }
        static::$variables[$key] = $value;
    }
}
