<?php
return array(
		array(
			"name"=>"period_menu",
			"label"=>"Period",
			"subnav"=>array(
				array(
					"name"=>"close_month_period",
					"label"=>"Close Monthly",
					"controller"=>"close_month_period",
					"method"=>"index",
				),
			),
			"requirements"=>array(
				"accounting_calculation"=>"period",
			),
		),
		array(
			"name"=>"accounting_coa_menu",
			"label"=>"COA",
			"subnav"=>array(
				array(
					"name"=>"accounting_coa_class",
					"label"=>"COA Class",
					"controller"=>"accounting_coa_class",
					"method"=>"index",
					"action"=>array(
						array(
							'name'=>'add_accounting_coa_class',
							'label'=>'Add',
							'controller'=>'accounting_coa_class',
							'method'=>'add',
						),
						array(
							'name'=>'edit_accounting_coa_class',
							'label'=>'Edit',
							'controller'=>'accounting_coa_class',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_accounting_coa_class',
							'label'=>'Delete',
							'controller'=>'accounting_coa_class',
							'method'=>'delete',
						),
					),
				),
				
				array(
					"name"=>"accounting_coa",
					"label"=>"COA",
					"controller"=>"accounting_coa",
					"method"=>"index",
					"action"=>array(
						array(
							'name'=>'add_accounting_coa',
							'label'=>'Add',
							'controller'=>'accounting_coa',
							'method'=>'add',
						),
						array(
							'name'=>'edit_accounting_coa',
							'label'=>'Edit',
							'controller'=>'accounting_coa',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_accounting_coa',
							'label'=>'Delete',
							'controller'=>'accounting_coa',
							'method'=>'delete',
						),
					),
				),
			),
		),
		array(
			"name"=>"posting_menu",
			"label"=>"Posting",
			'subnav'=>array(
				array(
					"name"=>"posting_queue",
					"label"=>"Posting Queue",
					'controller'=>'posting_queue',
					'method'=>'index',
				),
			),
		),
		array(
			"name"=>"accounting_coa_config",
			"label"=>"COA Config",
			'controller'=>'accounting_coa_config',
			'method'=>'index',
		),
		array(
			"name"=>"period",
			"label"=>"Period",
			'controller'=>'period',
			'method'=>'index',
		),
	);