<?php
return array(
		array(
			"name"=>"employee_list",
			"label"=>"Employee Data",
			"subnav"=>array(
				array(
					"name"=>"employee",
					"label"=>"Employee",
					"controller"=>"employee",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_employee',
							'label'=>'Add',
							'controller'=>'employee',
							'method'=>'add',
						),
						array(
							'name'=>'edit_employee',
							'label'=>'Edit',
							'controller'=>'employee',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_employee',
							'label'=>'Delete',
							'controller'=>'employee',
							'method'=>'delete',
						),
					), //end action employee
					"requirements"=>array(
						"have_employee"=>true,
					),
				), //end employee
				array(
					"name"=>"salesman",
					"label"=>"Salesman",
					"controller"=>"salesman",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_salesman',
							'label'=>'Add',
							'controller'=>'salesman',
							'method'=>'add',
						),
						array(
							'name'=>'edit_salesman',
							'label'=>'Edit',
							'controller'=>'salesman',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_salesman',
							'label'=>'Delete',
							'controller'=>'salesman',
							'method'=>'delete',
						),
					), //end action salesman
					"requirements"=>array(
						"have_salesman"=>true,
					),
				), //end salesman
			),
		),
		array(
			"name"=>"customer",
			"label"=>"Customer",
			"controller"=>"customer",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'detail_customer',
					'label'=>'Detail',
					'controller'=>'customer',
					'method'=>'detail',
				),
				array(
					'name'=>'add_customer',
					'label'=>'Add',
					'controller'=>'customer',
					'method'=>'add',
				),
				array(
					'name'=>'edit_customer',
					'label'=>'Edit',
					'controller'=>'customer',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_customer',
					'label'=>'Delete',
					'controller'=>'customer',
					'method'=>'delete',
				),
			),
			"requirements"=>array(
				"have_customer"=>true,
			),
		),
		array(
			"name"=>"supplier",
			"label"=>"Supplier",
			"controller"=>"supplier",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'detail_supplier',
					'label'=>'Detail',
					'controller'=>'supplier',
					'method'=>'detail',
				),
				array(
					'name'=>'add_supplier',
					'label'=>'Add',
					'controller'=>'supplier',
					'method'=>'add',
				),
				array(
					'name'=>'edit_supplier',
					'label'=>'Edit',
					'controller'=>'supplier',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_supplier',
					'label'=>'Delete',
					'controller'=>'supplier',
					'method'=>'delete',
				),
			),
			"requirements"=>array(
				"have_supplier"=>true,
			),
		),
		array(
			"name"=>"expedition",
			"label"=>"Expedition",
			"controller"=>"expedition",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_expedition',
					'label'=>'Add',
					'controller'=>'expedition',
					'method'=>'add',
				),
				array(
					'name'=>'edit_expedition',
					'label'=>'Edit',
					'controller'=>'expedition',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_expedition',
					'label'=>'Delete',
					'controller'=>'expedition',
					'method'=>'delete',
				),
			),
			"requirements"=>array(
				"have_expedition"=>true,
			),
		),
		array(
			"name"=>"business_partner",
			"label"=>"Business Partner",
			"controller"=>"business_partner",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_business_partner',
					'label'=>'Add',
					'controller'=>'business_partner',
					'method'=>'add',
				),
				array(
					'name'=>'edit_business_partner',
					'label'=>'Edit',
					'controller'=>'business_partner',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_business_partner',
					'label'=>'Delete',
					'controller'=>'business_partner',
					'method'=>'delete',
				),
			), //end action business_partner_menu
			"requirements"=>array(
				"have_business_partner"=>true,
			),
		), //end business_partner_menu
	);
	