<?php

return array(
		array(
			"name"=>"item_list",
			"label"=>"Item",
			"subnav"=>array(
				array(
					"name"=>"item_brand",
					"label"=>"Item Brand",
					"controller"=>"item_brand",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_brand',
							'label'=>'Add',
							'controller'=>'item_brand',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_brand',
							'label'=>'Edit',
							'controller'=>'item_brand',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_brand',
							'label'=>'Delete',
							'controller'=>'item_brand',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"item_brand"=>true,
					),
				),
				array(
					"name"=>"item_type",
					"label"=>"Item Type",
					"controller"=>"item_type",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_type',
							'label'=>'Add',
							'controller'=>'item_type',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_type',
							'label'=>'Edit',
							'controller'=>'item_type',
							'method'=>'edit',
						),
						array(
							'name'=>'order_item_type',
							'label'=>'Change Order',
							'controller'=>'item_type',
							'method'=>'ordering',
						),
						array(
							'name'=>'delete_item_type',
							'label'=>'Delete',
							'controller'=>'item_type',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"item_type"=>true,
					),
				),
				array(
					"name"=>"item_tag",
					"label"=>"Item Tag",
					"controller"=>"item_tag",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_tag',
							'label'=>'Add',
							'controller'=>'item_tag',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_tag',
							'label'=>'Edit',
							'controller'=>'item_tag',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_tag',
							'label'=>'Delete',
							'controller'=>'item_tag',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"item_tag"=>true,
					),
				),
				array(
					"name"=>"item_rack",
					"label"=>"Item Rack",
					"controller"=>"item_rack",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_rack',
							'label'=>'Add',
							'controller'=>'item_rack',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_rack',
							'label'=>'Edit',
							'controller'=>'item_rack',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_rack',
							'label'=>'Delete',
							'controller'=>'item_rack',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"have_item_rack"=>true,
					),
				),
				array(
					"name"=>"item_category",
					"label"=>"Item Category",
					"controller"=>"item_category",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_category',
							'label'=>'Add',
							'controller'=>'item_category',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_category',
							'label'=>'Edit',
							'controller'=>'item_category',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_category',
							'label'=>'Delete',
							'controller'=>'item_category',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"item_category"=>true,
					),
				),
				array(
					"name"=>"item_subcategory",
					"label"=>"Item Subcategory",
					"controller"=>"item_subcategory",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_subcategory',
							'label'=>'Add',
							'controller'=>'item_subcategory',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_subcategory',
							'label'=>'Edit',
							'controller'=>'item_subcategory',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_subcategory',
							'label'=>'Delete',
							'controller'=>'item_subcategory',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"item_subcategory"=>true,
					),
				),
				array(
					"name"=>"item",
					"label"=>"Item",
					"controller"=>"item",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'detail_item',
							'label'=>'Detail',
							'controller'=>'item',
							'method'=>'detail',
						),
						array(
							'name'=>'add_item',
							'label'=>'Add',
							'controller'=>'item',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item',
							'label'=>'Edit',
							'controller'=>'item',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item',
							'label'=>'Delete',
							'controller'=>'item',
							'method'=>'delete',
						),
					),
				),
				array(
					"name"=>"item_batch",
					"label"=>"Item Batch",
					"controller"=>"item_batch",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'add_item_batch',
							'label'=>'Add',
							'controller'=>'item_batch',
							'method'=>'add',
						),
						array(
							'name'=>'edit_item_batch',
							'label'=>'Edit',
							'controller'=>'item_batch',
							'method'=>'edit',
						),
						array(
							'name'=>'delete_item_batch',
							'label'=>'Delete',
							'controller'=>'item_batch',
							'method'=>'delete',
						),
						
					),
					"requirements"=>array(
						"have_item_batch"=>true,
					),
				),
			),
		),
		array(
			"name"=>"unit",
			"label"=>"Unit",
			"controller"=>"unit",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_unit',
					'label'=>'Add',
					'controller'=>'unit',
					'method'=>'add',
				),
				array(
					'name'=>'edit_unit',
					'label'=>'Edit',
					'controller'=>'unit',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_unit',
					'label'=>'Delete',
					'controller'=>'unit',
					'method'=>'delete',
				),
				
			),
			"requirements"=>array(
				"have_unit"=>true,
			),
		),
		
		array(
			"name"=>"bom_menu",
			"label"=>"BOM Menu",
			"requirements"=>array(
				"have_resto_store"=>true,
			),
			"controller"=>"bom_menu",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_bom_menu',
					'label'=>'Add',
					'controller'=>'bom_menu',
					'method'=>'add',
				),
				array(
					'name'=>'edit_bom_menu',
					'label'=>'Edit',
					'controller'=>'bom_menu',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_bom_menu',
					'label'=>'Delete',
					'controller'=>'bom_menu',
					'method'=>'delete',
				),
				
			),
		),
		array(
			"name"=>"bom",
			"label"=>"BOM",
			"controller"=>"bom",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_bom',
					'label'=>'Add',
					'controller'=>'bom',
					'method'=>'add',
				),
				array(
					'name'=>'edit_bom',
					'label'=>'Edit',
					'controller'=>'bom',
					'method'=>'edit',
				),
				array(
					'name'=>'delete_bom',
					'label'=>'Delete',
					'controller'=>'bom',
					'method'=>'delete',
				),
				
			),
			"requirements"=>array(
				"have_bom"=>true,
			),
		),
		array(
			"name"=>"assembly_menu",
			"label"=>"Assembly",
			"subnav"=>array(
				array(
					"name"=>"assembly",
					"label"=>"Assembly",
					"controller"=>"assembly/add",
					"method"=>"index",
					
				),
				
				array(
					"name"=>"assembly_list",
					"label"=>"Assembly List",
					"controller"=>"assembly",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'detail_assembly',
							'label'=>'Detail',
							'controller'=>'assembly',
							'method'=>'detail',
						),
						array(
							'name'=>'delete_assembly',
							'label'=>'Delete Assembly',
							'controller'=>'assembly',
							'method'=>'delete',
						),
					),	
				),
				array(
					"name"=>"disassembly",
					"label"=>"Disassembly",
					"controller"=>"disassembly/add",
					"method"=>"index",
					
				),
				array(
					"name"=>"disassembly_list",
					"label"=>"Disassembly List",
					"controller"=>"disassembly",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'detail_disassembly',
							'label'=>'Detail',
							'controller'=>'disassembly',
							'method'=>'detail',
						),
						array(
							'name'=>'delete_disassembly',
							'label'=>'Delete Disassembly',
							'controller'=>'disassembly',
							'method'=>'delete',
						),
					),	
				),
			),
			"requirements"=>array(
				"have_bom"=>true,
				
			),
		),
		array(
			"name"=>"production_menu",
			"label"=>"Production",
			"subnav"=>array(
				array(
					"name"=>"production",
					"label"=>"Production",
					"controller"=>"production/add",
					"method"=>"index",
					
				),
				array(
					"name"=>"production_list",
					"label"=>"Production List",
					"controller"=>"production",
					"method"=>"index",
					'action'=>array(
						array(
							'name'=>'detail_production',
							'label'=>'Detail',
							'controller'=>'production',
							'method'=>'detail',
						),
						array(
							'name'=>'delete_production',
							'label'=>'Delete Production',
							'controller'=>'production',
							'method'=>'delete',
						),
					),	
				),
				
			),
			"requirements"=>array(
				"have_production"=>true,
			),
		),
		array(
			"name"=>"item_transfer",
			"label"=>"Item Transfer",
			"controller"=>"item_transfer",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_item_transfer',
					'label'=>'Add',
					'controller'=>'item_transfer',
					'method'=>'add',
				),
				
				
			),
			"requirements"=>array(
				"have_warehouse"=>true,
			),
		),
		array(
			"name"=>"stock_opname",
			"label"=>"Stock Opname",
			"controller"=>"stock_opname",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_stock_opname',
					'label'=>'Add',
					'controller'=>'stock_opname',
					'method'=>'add',
				),
				
				
			),
			"requirements"=>array(
				"have_warehouse"=>false,
			),
		),
		
		array(
			"name"=>"stock_opname_warehouse",
			"label"=>"Stock Opname Warehouse",
			"controller"=>"stock_opname_warehouse",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_stock_opname_warehouse',
					'label'=>'Add',
					'controller'=>'stock_opname_warehouse',
					'method'=>'add',
				),
				array(
					'name'=>'add_one_stock_opname_warehouse',
					'label'=>'Add One',
					'controller'=>'stock_opname_warehouse',
					'method'=>'add_one',
				),
				
			),
			"requirements"=>array(
				"have_warehouse"=>true,
			),
		),
		array(
			"name"=>"cogs_opname",
			"label"=>"COGS Opname",
			"controller"=>"cogs_opname",
			"method"=>"index",
			'action'=>array(
				array(
					'name'=>'add_cogs_opname',
					'label'=>'Add',
					'controller'=>'cogs_opname',
					'method'=>'add',
				),
				
				
			),
			"requirements"=>array(
				"have_cogs_opname"=>true,
			),
		),
	);
	