<?php

namespace Cresenity\Demo\Model;

class Country extends \CModel {
    use \CModel_ArrayDriver_ArrayDriverTrait;

    protected $rows = [
        ['code' => 'AF', 'code3' => 'AFG', 'num' => '004', 'isd' => '93', 'name' => 'Afghanistan', 'continent' => 'Asia', ],
        ['code' => 'AX', 'code3' => 'ALA', 'num' => '248', 'isd' => '358', 'name' => 'Åland Islands', 'continent' => 'Europe'],
        ['code' => 'AL', 'code3' => 'ALB', 'num' => '008', 'isd' => '355', 'name' => 'Albania', 'continent' => 'Europe'],
        ['code' => 'DZ', 'code3' => 'DZA', 'num' => '012', 'isd' => '213', 'name' => 'Algeria', 'continent' => 'Africa'],
        ['code' => 'AS', 'code3' => 'ASM', 'num' => '016', 'isd' => '1684', 'name' => 'American Samoa', 'continent' => 'Oceania'],
        ['code' => 'AD', 'code3' => 'AND', 'num' => '020', 'isd' => '376', 'name' => 'Andorra', 'continent' => 'Europe'],
        ['code' => 'AO', 'code3' => 'AGO', 'num' => '024', 'isd' => '244', 'name' => 'Angola', 'continent' => 'Africa'],
        ['code' => 'AI', 'code3' => 'AIA', 'num' => '660', 'isd' => '1264', 'name' => 'Anguilla', 'continent' => 'North America'],
        ['code' => 'AQ', 'code3' => 'ATA', 'num' => '010', 'isd' => '672', 'name' => 'Antarctica', 'continent' => 'Antarctica'],
        ['code' => 'AG', 'code3' => 'ATG', 'num' => '028', 'isd' => '1268', 'name' => 'Antigua and Barbuda', 'continent' => 'North America'],
        ['code' => 'AR', 'code3' => 'ARG', 'num' => '032', 'isd' => '54', 'name' => 'Argentina', 'continent' => 'South America'],
        ['code' => 'AM', 'code3' => 'ARM', 'num' => '051', 'isd' => '374', 'name' => 'Armenia', 'continent' => 'Asia'],
        ['code' => 'AW', 'code3' => 'ABW', 'num' => '533', 'isd' => '297', 'name' => 'Aruba', 'continent' => 'North America'],
        ['code' => 'AU', 'code3' => 'AUS', 'num' => '036', 'isd' => '61', 'name' => 'Australia', 'continent' => 'Oceania'],
        ['code' => 'AT', 'code3' => 'AUT', 'num' => '040', 'isd' => '43', 'name' => 'Austria', 'continent' => 'Europe'],
        ['code' => 'AZ', 'code3' => 'AZE', 'num' => '031', 'isd' => '994', 'name' => 'Azerbaijan', 'continent' => 'Asia'],
        ['code' => 'BS', 'code3' => 'BHS', 'num' => '044', 'isd' => '1242', 'name' => 'Bahamas', 'continent' => 'North America'],
        ['code' => 'BH', 'code3' => 'BHR', 'num' => '048', 'isd' => '973', 'name' => 'Bahrain', 'continent' => 'Asia'],
        ['code' => 'BD', 'code3' => 'BGD', 'num' => '050', 'isd' => '880', 'name' => 'Bangladesh', 'continent' => 'Asia'],
        ['code' => 'BB', 'code3' => 'BRB', 'num' => '052', 'isd' => '1246', 'name' => 'Barbados', 'continent' => 'North America'],
        ['code' => 'BY', 'code3' => 'BLR', 'num' => '112', 'isd' => '375', 'name' => 'Belarus', 'continent' => 'Europe'],
        ['code' => 'BE', 'code3' => 'BEL', 'num' => '056', 'isd' => '32', 'name' => 'Belgium', 'continent' => 'Europe'],
        ['code' => 'BZ', 'code3' => 'BLZ', 'num' => '084', 'isd' => '501', 'name' => 'Belize', 'continent' => 'North America'],
        ['code' => 'BJ', 'code3' => 'BEN', 'num' => '204', 'isd' => '229', 'name' => 'Benin', 'continent' => 'Africa'],
        ['code' => 'BM', 'code3' => 'BMU', 'num' => '060', 'isd' => '1441', 'name' => 'Bermuda', 'continent' => 'North America'],
        ['code' => 'BT', 'code3' => 'BTN', 'num' => '064', 'isd' => '975', 'name' => 'Bhutan', 'continent' => 'Asia'],
        ['code' => 'BO', 'code3' => 'BOL', 'num' => '068', 'isd' => '591', 'name' => 'Bolivia', 'continent' => 'South America'],
        ['code' => 'BQ', 'code3' => 'BES', 'num' => '535', 'isd' => '599', 'name' => 'Bonaire, Sint Eustatius and Saba', 'continent' => 'North America'],
        ['code' => 'BA', 'code3' => 'BIH', 'num' => '070', 'isd' => '387', 'name' => 'Bosnia and Herzegovina', 'continent' => 'Europe'],
        ['code' => 'BW', 'code3' => 'BWA', 'num' => '072', 'isd' => '267', 'name' => 'Botswana', 'continent' => 'Africa'],
        ['code' => 'BV', 'code3' => 'BVT', 'num' => '074', 'isd' => '61', 'name' => 'Bouvet Island', 'continent' => 'Antarctica'],
        ['code' => 'BR', 'code3' => 'BRA', 'num' => '076', 'isd' => '55', 'name' => 'Brazil', 'continent' => 'South America'],
        ['code' => 'IO', 'code3' => 'IOT', 'num' => '086', 'isd' => '246', 'name' => 'British Indian Ocean Territory', 'continent' => 'Asia'],
        ['code' => 'BN', 'code3' => 'BRN', 'num' => '096', 'isd' => '672', 'name' => 'Brunei Darussalam', 'continent' => 'Asia'],
        ['code' => 'BG', 'code3' => 'BGR', 'num' => '100', 'isd' => '359', 'name' => 'Bulgaria', 'continent' => 'Europe'],
        ['code' => 'BF', 'code3' => 'BFA', 'num' => '854', 'isd' => '226', 'name' => 'Burkina Faso', 'continent' => 'Africa'],
        ['code' => 'BI', 'code3' => 'BDI', 'num' => '108', 'isd' => '257', 'name' => 'Burundi', 'continent' => 'Africa'],
        ['code' => 'KH', 'code3' => 'KHM', 'num' => '116', 'isd' => '855', 'name' => 'Cambodia', 'continent' => 'Asia'],
        ['code' => 'CM', 'code3' => 'CMR', 'num' => '120', 'isd' => '231', 'name' => 'Cameroon', 'continent' => 'Africa'],
        ['code' => 'CA', 'code3' => 'CAN', 'num' => '124', 'isd' => '1', 'name' => 'Canada', 'continent' => 'North America'],
        ['code' => 'CV', 'code3' => 'CPV', 'num' => '132', 'isd' => '238', 'name' => 'Cape Verde', 'continent' => 'Africa'],
        ['code' => 'KY', 'code3' => 'CYM', 'num' => '136', 'isd' => '1345', 'name' => 'Cayman Islands', 'continent' => 'North America'],
        ['code' => 'CF', 'code3' => 'CAF', 'num' => '140', 'isd' => '236', 'name' => 'Central African Republic', 'continent' => 'Africa'],
        ['code' => 'TD', 'code3' => 'TCD', 'num' => '148', 'isd' => '235', 'name' => 'Chad', 'continent' => 'Africa'],
        ['code' => 'CL', 'code3' => 'CHL', 'num' => '152', 'isd' => '56', 'name' => 'Chile', 'continent' => 'South America'],
        ['code' => 'CN', 'code3' => 'CHN', 'num' => '156', 'isd' => '86', 'name' => 'China', 'continent' => 'Asia'],
        ['code' => 'CX', 'code3' => 'CXR', 'num' => '162', 'isd' => '61', 'name' => 'Christmas Island', 'continent' => 'Asia'],
        ['code' => 'CC', 'code3' => 'CCK', 'num' => '166', 'isd' => '891', 'name' => 'Cocos (Keeling) Islands', 'continent' => 'Asia'],
        ['code' => 'CO', 'code3' => 'COL', 'num' => '170', 'isd' => '57', 'name' => 'Colombia', 'continent' => 'South America'],
        ['code' => 'KM', 'code3' => 'COM', 'num' => '174', 'isd' => '269', 'name' => 'Comoros', 'continent' => 'Africa'],
        ['code' => 'CG', 'code3' => 'COG', 'num' => '178', 'isd' => '242', 'name' => 'Congo', 'continent' => 'Africa'],
        ['code' => 'CD', 'code3' => 'COD', 'num' => '180', 'isd' => '243', 'name' => 'The Democratic Republic of The Congo', 'continent' => 'Africa'],
        ['code' => 'CK', 'code3' => 'COK', 'num' => '184', 'isd' => '682', 'name' => 'Cook Islands', 'continent' => 'Oceania'],
        ['code' => 'CR', 'code3' => 'CRI', 'num' => '188', 'isd' => '506', 'name' => 'Costa Rica', 'continent' => 'North America'],
        ['code' => 'CI', 'code3' => 'CIV', 'num' => '384', 'isd' => '225', 'name' => 'Cote D\'ivoire', 'continent' => 'Africa'],
        ['code' => 'CW', 'code3' => 'CUW', 'num' => '531', 'isd' => '599', 'name' => 'Curaçao', 'continent' => 'North America'],
        ['code' => 'HR', 'code3' => 'HRV', 'num' => '191', 'isd' => '385', 'name' => 'Croatia', 'continent' => 'Europe'],
        ['code' => 'CU', 'code3' => 'CUB', 'num' => '192', 'isd' => '53', 'name' => 'Cuba', 'continent' => 'North America'],
        ['code' => 'CY', 'code3' => 'CYP', 'num' => '196', 'isd' => '357', 'name' => 'Cyprus', 'continent' => 'Asia'],
        ['code' => 'CZ', 'code3' => 'CZE', 'num' => '203', 'isd' => '420', 'name' => 'Czech Republic', 'continent' => 'Europe'],
        ['code' => 'DK', 'code3' => 'DNK', 'num' => '208', 'isd' => '45', 'name' => 'Denmark', 'continent' => 'Europe'],
        ['code' => 'DJ', 'code3' => 'DJI', 'num' => '262', 'isd' => '253', 'name' => 'Djibouti', 'continent' => 'Africa'],
        ['code' => 'DM', 'code3' => 'DMA', 'num' => '212', 'isd' => '1767', 'name' => 'Dominica', 'continent' => 'North America'],
        ['code' => 'DO', 'code3' => 'DOM', 'num' => '214', 'isd' => '1809', 'name' => 'Dominican Republic', 'continent' => 'North America'],
        ['code' => 'EC', 'code3' => 'ECU', 'num' => '218', 'isd' => '593', 'name' => 'Ecuador', 'continent' => 'South America'],
        ['code' => 'EG', 'code3' => 'EGY', 'num' => '818', 'isd' => '20', 'name' => 'Egypt', 'continent' => 'Africa'],
        ['code' => 'SV', 'code3' => 'SLV', 'num' => '222', 'isd' => '503', 'name' => 'El Salvador', 'continent' => 'North America'],
        ['code' => 'GQ', 'code3' => 'GNQ', 'num' => '226', 'isd' => '240', 'name' => 'Equatorial Guinea', 'continent' => 'Africa'],
        ['code' => 'ER', 'code3' => 'ERI', 'num' => '232', 'isd' => '291', 'name' => 'Eritrea', 'continent' => 'Africa'],
        ['code' => 'EE', 'code3' => 'EST', 'num' => '233', 'isd' => '372', 'name' => 'Estonia', 'continent' => 'Europe'],
        ['code' => 'ET', 'code3' => 'ETH', 'num' => '231', 'isd' => '251', 'name' => 'Ethiopia', 'continent' => 'Africa'],
        ['code' => 'FK', 'code3' => 'FLK', 'num' => '238', 'isd' => '500', 'name' => 'Falkland Islands (Malvinas)', 'continent' => 'South America'],
        ['code' => 'FO', 'code3' => 'FRO', 'num' => '234', 'isd' => '298', 'name' => 'Faroe Islands', 'continent' => 'Europe'],
        ['code' => 'FJ', 'code3' => 'FJI', 'num' => '243', 'isd' => '679', 'name' => 'Fiji', 'continent' => 'Oceania'],
        ['code' => 'FI', 'code3' => 'FIN', 'num' => '246', 'isd' => '238', 'name' => 'Finland', 'continent' => 'Europe'],
        ['code' => 'FR', 'code3' => 'FRA', 'num' => '250', 'isd' => '33', 'name' => 'France', 'continent' => 'Europe'],
        ['code' => 'GF', 'code3' => 'GUF', 'num' => '254', 'isd' => '594', 'name' => 'French Guiana', 'continent' => 'South America'],
        ['code' => 'PF', 'code3' => 'PYF', 'num' => '258', 'isd' => '689', 'name' => 'French Polynesia', 'continent' => 'Oceania'],
        ['code' => 'TF', 'code3' => 'ATF', 'num' => '260', 'isd' => '262', 'name' => 'French Southern Territories', 'continent' => 'Antarctica'],
        ['code' => 'GA', 'code3' => 'GAB', 'num' => '266', 'isd' => '241', 'name' => 'Gabon', 'continent' => 'Africa'],
        ['code' => 'GM', 'code3' => 'GMB', 'num' => '270', 'isd' => '220', 'name' => 'Gambia', 'continent' => 'Africa'],
        ['code' => 'GE', 'code3' => 'GEO', 'num' => '268', 'isd' => '995', 'name' => 'Georgia', 'continent' => 'Asia'],
        ['code' => 'DE', 'code3' => 'DEU', 'num' => '276', 'isd' => '49', 'name' => 'Germany', 'continent' => 'Europe'],
        ['code' => 'GH', 'code3' => 'GHA', 'num' => '288', 'isd' => '233', 'name' => 'Ghana', 'continent' => 'Africa'],
        ['code' => 'GI', 'code3' => 'GIB', 'num' => '292', 'isd' => '350', 'name' => 'Gibraltar', 'continent' => 'Europe'],
        ['code' => 'GR', 'code3' => 'GRC', 'num' => '300', 'isd' => '30', 'name' => 'Greece', 'continent' => 'Europe'],
        ['code' => 'GL', 'code3' => 'GRL', 'num' => '304', 'isd' => '299', 'name' => 'Greenland', 'continent' => 'North America'],
        ['code' => 'GD', 'code3' => 'GRD', 'num' => '308', 'isd' => '1473', 'name' => 'Grenada', 'continent' => 'North America'],
        ['code' => 'GP', 'code3' => 'GLP', 'num' => '312', 'isd' => '590', 'name' => 'Guadeloupe', 'continent' => 'North America'],
        ['code' => 'GU', 'code3' => 'GUM', 'num' => '316', 'isd' => '1871', 'name' => 'Guam', 'continent' => 'Oceania'],
        ['code' => 'GT', 'code3' => 'GTM', 'num' => '320', 'isd' => '502', 'name' => 'Guatemala', 'continent' => 'North America'],
        ['code' => 'GG', 'code3' => 'GGY', 'num' => '831', 'isd' => '44', 'name' => 'Guernsey', 'continent' => 'Europe'],
        ['code' => 'GN', 'code3' => 'GIN', 'num' => '324', 'isd' => '224', 'name' => 'Guinea', 'continent' => 'Africa'],
        ['code' => 'GW', 'code3' => 'GNB', 'num' => '624', 'isd' => '245', 'name' => 'Guinea-bissau', 'continent' => 'Africa'],
        ['code' => 'GY', 'code3' => 'GUY', 'num' => '328', 'isd' => '592', 'name' => 'Guyana', 'continent' => 'South America'],
        ['code' => 'HT', 'code3' => 'HTI', 'num' => '332', 'isd' => '509', 'name' => 'Haiti', 'continent' => 'North America'],
        ['code' => 'HM', 'code3' => 'HMD', 'num' => '334', 'isd' => '672', 'name' => 'Heard Island and Mcdonald Islands', 'continent' => 'Antarctica'],
        ['code' => 'VA', 'code3' => 'VAT', 'num' => '336', 'isd' => '379', 'name' => 'Holy See (Vatican City State)', 'continent' => 'Europe'],
        ['code' => 'HN', 'code3' => 'HND', 'num' => '340', 'isd' => '504', 'name' => 'Honduras', 'continent' => 'North America'],
        ['code' => 'HK', 'code3' => 'HKG', 'num' => '344', 'isd' => '852', 'name' => 'Hong Kong', 'continent' => 'Asia'],
        ['code' => 'HU', 'code3' => 'HUN', 'num' => '348', 'isd' => '36', 'name' => 'Hungary', 'continent' => 'Europe'],
        ['code' => 'IS', 'code3' => 'ISL', 'num' => '352', 'isd' => '354', 'name' => 'Iceland', 'continent' => 'Europe'],
        ['code' => 'IN', 'code3' => 'IND', 'num' => '356', 'isd' => '91', 'name' => 'India', 'continent' => 'Asia'],
        ['code' => 'ID', 'code3' => 'IDN', 'num' => '360', 'isd' => '62', 'name' => 'Indonesia', 'continent' => 'Asia'],
        ['code' => 'IR', 'code3' => 'IRN', 'num' => '364', 'isd' => '98', 'name' => 'Iran', 'continent' => 'Asia'],
        ['code' => 'IQ', 'code3' => 'IRQ', 'num' => '368', 'isd' => '964', 'name' => 'Iraq', 'continent' => 'Asia'],
        ['code' => 'IE', 'code3' => 'IRL', 'num' => '372', 'isd' => '353', 'name' => 'Ireland', 'continent' => 'Europe'],
        ['code' => 'IM', 'code3' => 'IMN', 'num' => '833', 'isd' => '44', 'name' => 'Isle of Man', 'continent' => 'Europe'],
        ['code' => 'IL', 'code3' => 'ISR', 'num' => '376', 'isd' => '972', 'name' => 'Israel', 'continent' => 'Asia'],
        ['code' => 'IT', 'code3' => 'ITA', 'num' => '380', 'isd' => '39', 'name' => 'Italy', 'continent' => 'Europe'],
        ['code' => 'JM', 'code3' => 'JAM', 'num' => '388', 'isd' => '1876', 'name' => 'Jamaica', 'continent' => 'North America'],
        ['code' => 'JP', 'code3' => 'JPN', 'num' => '392', 'isd' => '81', 'name' => 'Japan', 'continent' => 'Asia'],
        ['code' => 'JE', 'code3' => 'JEY', 'num' => '832', 'isd' => '44', 'name' => 'Jersey', 'continent' => 'Europe'],
        ['code' => 'JO', 'code3' => 'JOR', 'num' => '400', 'isd' => '962', 'name' => 'Jordan', 'continent' => 'Asia'],
        ['code' => 'KZ', 'code3' => 'KAZ', 'num' => '398', 'isd' => '7', 'name' => 'Kazakhstan', 'continent' => 'Asia'],
        ['code' => 'KE', 'code3' => 'KEN', 'num' => '404', 'isd' => '254', 'name' => 'Kenya', 'continent' => 'Africa'],
        ['code' => 'KI', 'code3' => 'KIR', 'num' => '296', 'isd' => '686', 'name' => 'Kiribati', 'continent' => 'Oceania'],
        ['code' => 'KP', 'code3' => 'PRK', 'num' => '408', 'isd' => '850', 'name' => "Democratic People's Republic of Korea", 'continent' => 'Asia'],
        ['code' => 'KR', 'code3' => 'KOR', 'num' => '410', 'isd' => '82', 'name' => 'Republic of Korea', 'continent' => 'Asia'],
        ['code' => 'KW', 'code3' => 'KWT', 'num' => '414', 'isd' => '965', 'name' => 'Kuwait', 'continent' => 'Asia'],
        ['code' => 'KG', 'code3' => 'KGZ', 'num' => '417', 'isd' => '996', 'name' => 'Kyrgyzstan', 'continent' => 'Asia'],
        ['code' => 'LA', 'code3' => 'LAO', 'num' => '418', 'isd' => '856', 'name' => "Lao People's Democratic Republic", 'continent' => 'Asia'],
        ['code' => 'LV', 'code3' => 'LVA', 'num' => '428', 'isd' => '371', 'name' => 'Latvia', 'continent' => 'Europe'],
        ['code' => 'LB', 'code3' => 'LBN', 'num' => '422', 'isd' => '961', 'name' => 'Lebanon', 'continent' => 'Asia'],
        ['code' => 'LS', 'code3' => 'LSO', 'num' => '426', 'isd' => '266', 'name' => 'Lesotho', 'continent' => 'Africa'],
        ['code' => 'LR', 'code3' => 'LBR', 'num' => '430', 'isd' => '231', 'name' => 'Liberia', 'continent' => 'Africa'],
        ['code' => 'LY', 'code3' => 'LBY', 'num' => '434', 'isd' => '218', 'name' => 'Libya', 'continent' => 'Africa'],
        ['code' => 'LI', 'code3' => 'LIE', 'num' => '438', 'isd' => '423', 'name' => 'Liechtenstein', 'continent' => 'Europe'],
        ['code' => 'LT', 'code3' => 'LTU', 'num' => '440', 'isd' => '370', 'name' => 'Lithuania', 'continent' => 'Europe'],
        ['code' => 'LU', 'code3' => 'LUX', 'num' => '442', 'isd' => '352', 'name' => 'Luxembourg', 'continent' => 'Europe'],
        ['code' => 'MO', 'code3' => 'MAC', 'num' => '446', 'isd' => '853', 'name' => 'Macao', 'continent' => 'Asia'],
        ['code' => 'MK', 'code3' => 'MKD', 'num' => '807', 'isd' => '389', 'name' => 'Macedonia', 'continent' => 'Europe'],
        ['code' => 'MG', 'code3' => 'MDG', 'num' => '450', 'isd' => '261', 'name' => 'Madagascar', 'continent' => 'Africa'],
        ['code' => 'MW', 'code3' => 'MWI', 'num' => '454', 'isd' => '265', 'name' => 'Malawi', 'continent' => 'Africa'],
        ['code' => 'MY', 'code3' => 'MYS', 'num' => '458', 'isd' => '60', 'name' => 'Malaysia', 'continent' => 'Asia'],
        ['code' => 'MV', 'code3' => 'MDV', 'num' => '462', 'isd' => '960', 'name' => 'Maldives', 'continent' => 'Asia'],
        ['code' => 'ML', 'code3' => 'MLI', 'num' => '466', 'isd' => '223', 'name' => 'Mali', 'continent' => 'Africa'],
        ['code' => 'MT', 'code3' => 'MLT', 'num' => '470', 'isd' => '356', 'name' => 'Malta', 'continent' => 'Europe'],
        ['code' => 'MH', 'code3' => 'MHL', 'num' => '584', 'isd' => '692', 'name' => 'Marshall Islands', 'continent' => 'Oceania'],
        ['code' => 'MQ', 'code3' => 'MTQ', 'num' => '474', 'isd' => '596', 'name' => 'Martinique', 'continent' => 'North America'],
        ['code' => 'MR', 'code3' => 'MRT', 'num' => '478', 'isd' => '222', 'name' => 'Mauritania', 'continent' => 'Africa'],
        ['code' => 'MU', 'code3' => 'MUS', 'num' => '480', 'isd' => '230', 'name' => 'Mauritius', 'continent' => 'Africa'],
        ['code' => 'YT', 'code3' => 'MYT', 'num' => '175', 'isd' => '262', 'name' => 'Mayotte', 'continent' => 'Africa'],
        ['code' => 'MX', 'code3' => 'MEX', 'num' => '484', 'isd' => '52', 'name' => 'Mexico', 'continent' => 'North America'],
        ['code' => 'FM', 'code3' => 'FSM', 'num' => '583', 'isd' => '691', 'name' => 'Micronesia', 'continent' => 'Oceania'],
        ['code' => 'MD', 'code3' => 'MDA', 'num' => '498', 'isd' => '373', 'name' => 'Moldova', 'continent' => 'Europe'],
        ['code' => 'MC', 'code3' => 'MCO', 'num' => '492', 'isd' => '377', 'name' => 'Monaco', 'continent' => 'Europe'],
        ['code' => 'MN', 'code3' => 'MNG', 'num' => '496', 'isd' => '976', 'name' => 'Mongolia', 'continent' => 'Asia'],
        ['code' => 'ME', 'code3' => 'MNE', 'num' => '499', 'isd' => '382', 'name' => 'Montenegro', 'continent' => 'Europe'],
        ['code' => 'MS', 'code3' => 'MSR', 'num' => '500', 'isd' => '1664', 'name' => 'Montserrat', 'continent' => 'North America'],
        ['code' => 'MA', 'code3' => 'MAR', 'num' => '504', 'isd' => '212', 'name' => 'Morocco', 'continent' => 'Africa'],
        ['code' => 'MZ', 'code3' => 'MOZ', 'num' => '508', 'isd' => '258', 'name' => 'Mozambique', 'continent' => 'Africa'],
        ['code' => 'MM', 'code3' => 'MMR', 'num' => '104', 'isd' => '95', 'name' => 'Myanmar', 'continent' => 'Asia'],
        ['code' => 'NA', 'code3' => 'NAM', 'num' => '516', 'isd' => '264', 'name' => 'Namibia', 'continent' => 'Africa'],
        ['code' => 'NR', 'code3' => 'NRU', 'num' => '520', 'isd' => '674', 'name' => 'Nauru', 'continent' => 'Oceania'],
        ['code' => 'NP', 'code3' => 'NPL', 'num' => '524', 'isd' => '977', 'name' => 'Nepal', 'continent' => 'Asia'],
        ['code' => 'NL', 'code3' => 'NLD', 'num' => '528', 'isd' => '31', 'name' => 'Netherlands', 'continent' => 'Europe'],
        ['code' => 'NC', 'code3' => 'NCL', 'num' => '540', 'isd' => '687', 'name' => 'New Caledonia', 'continent' => 'Oceania'],
        ['code' => 'NZ', 'code3' => 'NZL', 'num' => '554', 'isd' => '64', 'name' => 'New Zealand', 'continent' => 'Oceania'],
        ['code' => 'NI', 'code3' => 'NIC', 'num' => '558', 'isd' => '505', 'name' => 'Nicaragua', 'continent' => 'North America'],
        ['code' => 'NE', 'code3' => 'NER', 'num' => '562', 'isd' => '227', 'name' => 'Niger', 'continent' => 'Africa'],
        ['code' => 'NG', 'code3' => 'NGA', 'num' => '566', 'isd' => '234', 'name' => 'Nigeria', 'continent' => 'Africa'],
        ['code' => 'NU', 'code3' => 'NIU', 'num' => '570', 'isd' => '683', 'name' => 'Niue', 'continent' => 'Oceania'],
        ['code' => 'NF', 'code3' => 'NFK', 'num' => '574', 'isd' => '672', 'name' => 'Norfolk Island', 'continent' => 'Oceania'],
        ['code' => 'MP', 'code3' => 'MNP', 'num' => '580', 'isd' => '1670', 'name' => 'Northern Mariana Islands', 'continent' => 'Oceania'],
        ['code' => 'NO', 'code3' => 'NOR', 'num' => '578', 'isd' => '47', 'name' => 'Norway', 'continent' => 'Europe'],
        ['code' => 'OM', 'code3' => 'OMN', 'num' => '512', 'isd' => '968', 'name' => 'Oman', 'continent' => 'Asia'],
        ['code' => 'PK', 'code3' => 'PAK', 'num' => '586', 'isd' => '92', 'name' => 'Pakistan', 'continent' => 'Asia'],
        ['code' => 'PW', 'code3' => 'PLW', 'num' => '585', 'isd' => '680', 'name' => 'Palau', 'continent' => 'Oceania'],
        ['code' => 'PS', 'code3' => 'PSE', 'num' => '275', 'isd' => '970', 'name' => 'Palestinia', 'continent' => 'Asia'],
        ['code' => 'PA', 'code3' => 'PAN', 'num' => '591', 'isd' => '507', 'name' => 'Panama', 'continent' => 'North America'],
        ['code' => 'PG', 'code3' => 'PNG', 'num' => '598', 'isd' => '675', 'name' => 'Papua New Guinea', 'continent' => 'Oceania'],
        ['code' => 'PY', 'code3' => 'PRY', 'num' => '600', 'isd' => '595', 'name' => 'Paraguay', 'continent' => 'South America'],
        ['code' => 'PE', 'code3' => 'PER', 'num' => '604', 'isd' => '51', 'name' => 'Peru', 'continent' => 'South America'],
        ['code' => 'PH', 'code3' => 'PHL', 'num' => '608', 'isd' => '63', 'name' => 'Philippines', 'continent' => 'Asia'],
        ['code' => 'PN', 'code3' => 'PCN', 'num' => '612', 'isd' => '870', 'name' => 'Pitcairn', 'continent' => 'Oceania'],
        ['code' => 'PL', 'code3' => 'POL', 'num' => '616', 'isd' => '48', 'name' => 'Poland', 'continent' => 'Europe'],
        ['code' => 'PT', 'code3' => 'PRT', 'num' => '620', 'isd' => '351', 'name' => 'Portugal', 'continent' => 'Europe'],
        ['code' => 'PR', 'code3' => 'PRI', 'num' => '630', 'isd' => '1', 'name' => 'Puerto Rico', 'continent' => 'North America'],
        ['code' => 'QA', 'code3' => 'QAT', 'num' => '634', 'isd' => '974', 'name' => 'Qatar', 'continent' => 'Asia'],
        ['code' => 'RE', 'code3' => 'REU', 'num' => '638', 'isd' => '262', 'name' => 'Reunion', 'continent' => 'Africa'],
        ['code' => 'RO', 'code3' => 'ROU', 'num' => '642', 'isd' => '40', 'name' => 'Romania', 'continent' => 'Europe'],
        ['code' => 'RU', 'code3' => 'RUS', 'num' => '643', 'isd' => '7', 'name' => 'Russian Federation', 'continent' => 'Europe'],
        ['code' => 'RW', 'code3' => 'RWA', 'num' => '646', 'isd' => '250', 'name' => 'Rwanda', 'continent' => 'Africa'],
        ['code' => 'BL', 'code3' => 'BLM', 'num' => '652', 'isd' => '590', 'name' => 'Saint Barthélemy', 'continent' => 'North America'],
        ['code' => 'SH', 'code3' => 'SHN', 'num' => '654', 'isd' => '290', 'name' => 'Saint Helena', 'continent' => 'Africa'],
        ['code' => 'KN', 'code3' => 'KNA', 'num' => '659', 'isd' => '1869', 'name' => 'Saint Kitts and Nevis', 'continent' => 'North America'],
        ['code' => 'LC', 'code3' => 'LCA', 'num' => '662', 'isd' => '1758', 'name' => 'Saint Lucia', 'continent' => 'North America'],
        ['code' => 'MF', 'code3' => 'MAF', 'num' => '663', 'isd' => '590', 'name' => 'Saint Martin', 'continent' => 'North America'],
        ['code' => 'PM', 'code3' => 'SPM', 'num' => '666', 'isd' => '508', 'name' => 'Saint Pierre and Miquelon', 'continent' => 'North America'],
        ['code' => 'VC', 'code3' => 'VCT', 'num' => '670', 'isd' => '1784', 'name' => 'Saint Vincent and The Grenadines', 'continent' => 'North America'],
        ['code' => 'WS', 'code3' => 'WSM', 'num' => '882', 'isd' => '685', 'name' => 'Samoa', 'continent' => 'Oceania'],
        ['code' => 'SM', 'code3' => 'SMR', 'num' => '674', 'isd' => '378', 'name' => 'San Marino', 'continent' => 'Europe'],
        ['code' => 'ST', 'code3' => 'STP', 'num' => '678', 'isd' => '239', 'name' => 'Sao Tome and Principe', 'continent' => 'Africa'],
        ['code' => 'SA', 'code3' => 'SAU', 'num' => '682', 'isd' => '966', 'name' => 'Saudi Arabia', 'continent' => 'Asia'],
        ['code' => 'SN', 'code3' => 'SEN', 'num' => '686', 'isd' => '221', 'name' => 'Senegal', 'continent' => 'Africa'],
        ['code' => 'RS', 'code3' => 'SRB', 'num' => '688', 'isd' => '381', 'name' => 'Serbia', 'continent' => 'Europe'],
        ['code' => 'SC', 'code3' => 'SYC', 'num' => '690', 'isd' => '248', 'name' => 'Seychelles', 'continent' => 'Africa'],
        ['code' => 'SL', 'code3' => 'SLE', 'num' => '694', 'isd' => '232', 'name' => 'Sierra Leone', 'continent' => 'Africa'],
        ['code' => 'SG', 'code3' => 'SGP', 'num' => '702', 'isd' => '65', 'name' => 'Singapore', 'continent' => 'Asia'],
        ['code' => 'SX', 'code3' => 'SXM', 'num' => '534', 'isd' => '1721', 'name' => 'Sint Maarten', 'continent' => 'North America'],
        ['code' => 'SK', 'code3' => 'SVK', 'num' => '703', 'isd' => '421', 'name' => 'Slovakia', 'continent' => 'Europe'],
        ['code' => 'SI', 'code3' => 'SVN', 'num' => '705', 'isd' => '386', 'name' => 'Slovenia', 'continent' => 'Europe'],
        ['code' => 'SB', 'code3' => 'SLB', 'num' => '090', 'isd' => '677', 'name' => 'Solomon Islands', 'continent' => 'Oceania'],
        ['code' => 'SO', 'code3' => 'SOM', 'num' => '706', 'isd' => '252', 'name' => 'Somalia', 'continent' => 'Africa'],
        ['code' => 'ZA', 'code3' => 'ZAF', 'num' => '729', 'isd' => '27', 'name' => 'South Africa', 'continent' => 'Africa'],
        ['code' => 'SS', 'code3' => 'SSD', 'num' => '710', 'isd' => '211', 'name' => 'South Sudan', 'continent' => 'Africa'],
        ['code' => 'GS', 'code3' => 'SGS', 'num' => '239', 'isd' => '500', 'name' => 'South Georgia and The South Sandwich Islands', 'continent' => 'Antarctica'],
        ['code' => 'ES', 'code3' => 'ESP', 'num' => '724', 'isd' => '34', 'name' => 'Spain', 'continent' => 'Europe'],
        ['code' => 'LK', 'code3' => 'LKA', 'num' => '144', 'isd' => '94', 'name' => 'Sri Lanka', 'continent' => 'Asia'],
        ['code' => 'SD', 'code3' => 'SDN', 'num' => '736', 'isd' => '249', 'name' => 'Sudan', 'continent' => 'Africa'],
        ['code' => 'SR', 'code3' => 'SUR', 'num' => '740', 'isd' => '597', 'name' => 'Suriname', 'continent' => 'South America'],
        ['code' => 'SJ', 'code3' => 'SJM', 'num' => '744', 'isd' => '47', 'name' => 'Svalbard and Jan Mayen', 'continent' => 'Europe'],
        ['code' => 'SZ', 'code3' => 'SWZ', 'num' => '748', 'isd' => '268', 'name' => 'Swaziland', 'continent' => 'Africa'],
        ['code' => 'SE', 'code3' => 'SWE', 'num' => '752', 'isd' => '46', 'name' => 'Sweden', 'continent' => 'Europe'],
        ['code' => 'CH', 'code3' => 'CHE', 'num' => '756', 'isd' => '41', 'name' => 'Switzerland', 'continent' => 'Europe'],
        ['code' => 'SY', 'code3' => 'SYR', 'num' => '760', 'isd' => '963', 'name' => 'Syrian Arab Republic', 'continent' => 'Asia'],
        ['code' => 'TW', 'code3' => 'TWN', 'num' => '158', 'isd' => '886', 'name' => 'Taiwan, Province of China', 'continent' => 'Asia'],
        ['code' => 'TJ', 'code3' => 'TJK', 'num' => '762', 'isd' => '992', 'name' => 'Tajikistan', 'continent' => 'Asia'],
        ['code' => 'TZ', 'code3' => 'TZA', 'num' => '834', 'isd' => '255', 'name' => 'Tanzania, United Republic of', 'continent' => 'Africa'],
        ['code' => 'TH', 'code3' => 'THA', 'num' => '764', 'isd' => '66', 'name' => 'Thailand', 'continent' => 'Asia'],
        ['code' => 'TL', 'code3' => 'TLS', 'num' => '626', 'isd' => '670', 'name' => 'Timor-leste', 'continent' => 'Asia'],
        ['code' => 'TG', 'code3' => 'TGO', 'num' => '768', 'isd' => '228', 'name' => 'Togo', 'continent' => 'Africa'],
        ['code' => 'TK', 'code3' => 'TKL', 'num' => '772', 'isd' => '690', 'name' => 'Tokelau', 'continent' => 'Oceania'],
        ['code' => 'TO', 'code3' => 'TON', 'num' => '776', 'isd' => '676', 'name' => 'Tonga', 'continent' => 'Oceania'],
        ['code' => 'TT', 'code3' => 'TTO', 'num' => '780', 'isd' => '1868', 'name' => 'Trinidad and Tobago', 'continent' => 'North America'],
        ['code' => 'TN', 'code3' => 'TUN', 'num' => '788', 'isd' => '216', 'name' => 'Tunisia', 'continent' => 'Africa'],
        ['code' => 'TR', 'code3' => 'TUR', 'num' => '792', 'isd' => '90', 'name' => 'Turkey', 'continent' => 'Asia'],
        ['code' => 'TM', 'code3' => 'TKM', 'num' => '795', 'isd' => '993', 'name' => 'Turkmenistan', 'continent' => 'Asia'],
        ['code' => 'TC', 'code3' => 'TCA', 'num' => '796', 'isd' => '1649', 'name' => 'Turks and Caicos Islands', 'continent' => 'North America'],
        ['code' => 'TV', 'code3' => 'TUV', 'num' => '798', 'isd' => '688', 'name' => 'Tuvalu', 'continent' => 'Oceania'],
        ['code' => 'UG', 'code3' => 'UGA', 'num' => '800', 'isd' => '256', 'name' => 'Uganda', 'continent' => 'Africa'],
        ['code' => 'UA', 'code3' => 'UKR', 'num' => '804', 'isd' => '380', 'name' => 'Ukraine', 'continent' => 'Europe'],
        ['code' => 'AE', 'code3' => 'ARE', 'num' => '784', 'isd' => '971', 'name' => 'United Arab Emirates', 'continent' => 'Asia'],
        ['code' => 'GB', 'code3' => 'GBR', 'num' => '826', 'isd' => '44', 'name' => 'United Kingdom', 'continent' => 'Europe'],
        ['code' => 'US', 'code3' => 'USA', 'num' => '840', 'isd' => '1', 'name' => 'United States', 'continent' => 'North America'],
        ['code' => 'UM', 'code3' => 'UMI', 'num' => '581', 'isd' => '1', 'name' => 'United States Minor Outlying Islands', 'continent' => 'Oceania'],
        ['code' => 'UY', 'code3' => 'URY', 'num' => '858', 'isd' => '598', 'name' => 'Uruguay', 'continent' => 'South America'],
        ['code' => 'UZ', 'code3' => 'UZB', 'num' => '860', 'isd' => '998', 'name' => 'Uzbekistan', 'continent' => 'Asia'],
        ['code' => 'VU', 'code3' => 'VUT', 'num' => '548', 'isd' => '678', 'name' => 'Vanuatu', 'continent' => 'Oceania'],
        ['code' => 'VE', 'code3' => 'VEN', 'num' => '862', 'isd' => '58', 'name' => 'Venezuela', 'continent' => 'South America'],
        ['code' => 'VN', 'code3' => 'VNM', 'num' => '704', 'isd' => '84', 'name' => 'Vietnam', 'continent' => 'Asia'],
        ['code' => 'VG', 'code3' => 'VGB', 'num' => '092', 'isd' => '1284', 'name' => 'Virgin Islands, British', 'continent' => 'North America'],
        ['code' => 'VI', 'code3' => 'VIR', 'num' => '850', 'isd' => '1430', 'name' => 'Virgin Islands, U.S.', 'continent' => 'North America'],
        ['code' => 'WF', 'code3' => 'WLF', 'num' => '876', 'isd' => '681', 'name' => 'Wallis and Futuna', 'continent' => 'Oceania'],
        ['code' => 'EH', 'code3' => 'ESH', 'num' => '732', 'isd' => '212', 'name' => 'Western Sahara', 'continent' => 'Africa'],
        ['code' => 'YE', 'code3' => 'YEM', 'num' => '887', 'isd' => '967', 'name' => 'Yemen', 'continent' => 'Asia'],
        ['code' => 'ZM', 'code3' => 'ZMB', 'num' => '894', 'isd' => '260', 'name' => 'Zambia', 'continent' => 'Africa'],
        ['code' => 'ZW', 'code3' => 'ZWE', 'num' => '716', 'isd' => '263', 'name' => 'Zimbabwe', 'continent' => 'Africa']
    ];
}
